define ob_terezi = Character("gallowsCallibrator", kind=trollean, what_color="#008282", image="ob_terezi", window_background="gui/textbox_trollian_teal.png")
image ob_terezi idle = Image("{{assets}}/dialogs/terezi/terezi_idle.png", yoffset=-197, xanchor=240, yalign=1.0)
image ob_terezi sad = Image("{{assets}}/dialogs/terezi/terezi_sad.png", yoffset=-197, xanchor=240, yalign=1.0)
image ob_terezi idle = Image("{{assets}}/dialogs/terezi/terezi_idle.png", yoffset=-197, xanchor=240, yalign=1.0)
image ob_terezi sad = Image("{{assets}}/dialogs/terezi/terezi_sad.png", yoffset=-197, xanchor=240, yalign=1.0)
