# ../custom_volumes_other/hiveswap\amisia.rpy
define amisia = Character(name="AMISIA", kind=hiveswap, image="amisia", window_background="gui/textbox_blue.png", who_outlines=[(4, "#000056")])

image amisia axe = Image("{{assets}}/sprite/amisia_axe.png", ypos=730)
image amisia blur2 = Image("{{assets}}/sprite/amisia_blur2.png", ypos=730)
image amisia confess = Image("{{assets}}/sprite/amisia_confess.png", ypos=730)
image amisia doubt = Image("{{assets}}/sprite/amisia_doubt.png", ypos=730)
image amisia frame = Image("{{assets}}/sprite/amisia_frame.png", ypos=730)
image amisia growl = Image("{{assets}}/sprite/amisia_growl.png", ypos=730)
image amisia hairpull = Image("{{assets}}/sprite/amisia_hairpull.png", ypos=730)
image amisia hop = Image("{{assets}}/sprite/amisia_hop.png", ypos=730)
image amisia nya = Image("{{assets}}/sprite/amisia_nya.png", ypos=730)
image amisia ponder = Image("{{assets}}/sprite/amisia_ponder.png", ypos=730)
image amisia smile = Image("{{assets}}/sprite/amisia_smile.png", ypos=730)
image amisia smile2 = Image("{{assets}}/sprite/amisia_smile2.png", ypos=730)
image amisia smug = Image("{{assets}}/sprite/amisia_smug.png", ypos=730)

init python:
    quirks["amisia"] = [("u", "uu")]

# ../custom_volumes_other/hiveswap\ardata.rpy
define ardata = Character(name="ARDATA", kind=hiveswap, image="ardata", window_background="gui/textbox_cobalt.png", who_outlines=[(4, "#005682")])

image ardata bored = Image("{{assets}}/sprite/ardata_bored.png", ypos=730)
image ardata cry = Image("{{assets}}/sprite/ardata_cry.png", ypos=730)
image ardata hand = Image("{{assets}}/sprite/ardata_hand.png", ypos=730)
image ardata laugh = Image("{{assets}}/sprite/ardata_laugh.png", ypos=730)
image ardata murder = Image("{{assets}}/sprite/ardata_murder.png", ypos=730)
image ardata ohoho = Image("{{assets}}/sprite/ardata_ohoho.png", ypos=730)
image ardata smile = Image("{{assets}}/sprite/ardata_smile.png", ypos=730)
image ardata testy = Image("{{assets}}/sprite/ardata_testy.png", ypos=730)
image ardata wink = Image("{{assets}}/sprite/ardata_wink.png", ypos=730)

# ../custom_volumes_other/hiveswap\azdaja.rpy
define azdaja = Character(name="AZDAJA", kind=hiveswap, image="azdaja", window_background="gui/textbox_gold.png", who_outlines=[(4, "#a1a100")])

image azdaja analize = Image("{{assets}}/sprite/Azdaja_analize.png", ypos=730)
image azdaja bragging = Image("{{assets}}/sprite/Azdaja_bragging.png", ypos=730)
image azdaja controlled = Image("{{assets}}/sprite/Azdaja_controlled.png", ypos=730)
image azdaja embarrased = Image("{{assets}}/sprite/Azdaja_embarrased.png", ypos=730)
image azdaja neutral = Image("{{assets}}/sprite/Azdaja_neutral.png", ypos=730)
image azdaja pissed = Image("{{assets}}/sprite/Azdaja_pissed.png", ypos=730)
image azdaja power1 = Image("{{assets}}/sprite/Azdaja_power1.png", ypos=730)
image azdaja power2 = Image("{{assets}}/sprite/Azdaja_power2.png", ypos=730)
image azdaja power3 = Image("{{assets}}/sprite/Azdaja_power3.png", ypos=730)
image azdaja power4 = Image("{{assets}}/sprite/Azdaja_power4.png", ypos=730)
image azdaja sayonara = Image("{{assets}}/sprite/Azdaja_sayonara.png", ypos=730)
image azdaja surprise = Image("{{assets}}/sprite/Azdaja_surprise.png", ypos=730)

init python:
    quirks["azdaja"] = [("(.+)", "||| \g<1> |||")]

# ../custom_volumes_other/hiveswap\backgrounds.rpy
image bg alley = Image("{{assets}}/bg/alley.png")
image bg alley2 = Image("{{assets}}/bg/alley2.png")
image bg alternia = Image("{{assets}}/bg/alternia.png")
image bg amisia_studio = Image("{{assets}}/bg/amisia_studio.png")
image bg ardata_basement = Image("{{assets}}/bg/ardata_basement.png")
image bg ardata_kitchen = Image("{{assets}}/bg/ardata_kitchen.png")
image bg arena3 = Image("{{assets}}/bg/arena3.png")
image bg arena4 = Image("{{assets}}/bg/arena4.png")
image bg hs_background1 = Image("{{assets}}/bg/background1.png")
image bg hs_background2 = Image("{{assets}}/bg/background2.png")
image bg hs_background3 = Image("{{assets}}/bg/background3.png")
image bg hs_background4 = Image("{{assets}}/bg/background4.png")
image bg background_spaceship = Image("{{assets}}/bg/background_spaceship.png")
image bg backstage3 = Image("{{assets}}/bg/backstage3.png")
image bg BG_karako_dark_carnival = Image("{{assets}}/bg/BG_karako_dark_carnival.png")
image bg BG_karako_undergrowth_1 = Image("{{assets}}/bg/BG_karako_undergrowth_1.png")
image bg BG_karako_undergrowth_2 = Image("{{assets}}/bg/BG_karako_undergrowth_2.png")
image bg BG_marsti_wall = Image("{{assets}}/bg/BG_marsti_wall.png")
image bg brainroom_final = Image("{{assets}}/bg/brainroom_final.png")
image bg bronya_cave = Image("{{assets}}/bg/bronya_cave.png")
image bg bronya_nursery = Image("{{assets}}/bg/bronya_nursery.png")
image bg Canyon = Image("{{assets}}/bg/Canyon.png")
image bg Cave = Image("{{assets}}/bg/Cave.png")
image bg cave_final = Image("{{assets}}/bg/cave_final.png")
image bg Chixie_Backdoor = Image("{{assets}}/bg/Chixie_Backdoor.png")
image bg Chixie_dressingroom = Image("{{assets}}/bg/Chixie_dressingroom.png")
image bg ciravablock = Image("{{assets}}/bg/ciravablock.png")
image bg ciravastream = Image("{{assets}}/bg/ciravastream.png")
image bg clownfest-close = Image("{{assets}}/bg/clownfest-close.png")
image bg clownfest = Image("{{assets}}/bg/clownfest.png")
image bg clown_church = Image("{{assets}}/bg/clown_church.png")
image bg clown_church_2 = Image("{{assets}}/bg/clown_church_2.png")
image bg clown_church_3 = Image("{{assets}}/bg/clown_church_3.png")
image bg clown_church_bw = Image("{{assets}}/bg/clown_church_bw.png")
image bg Coffee shop = Image("{{assets}}/bg/Coffee shop.png")
image bg desert = Image("{{assets}}/bg/desert.png")
image bg desertnight = Image("{{assets}}/bg/desertnight.png")
image bg elwurd hive = Image("{{assets}}/bg/elwurd hive.png")
image bg field-2-nolight = Image("{{assets}}/bg/field-2-nolight.png")
image bg field-2 = Image("{{assets}}/bg/field-2.png")
image bg field-nosign = Image("{{assets}}/bg/field-nosign.png")
image bg field-sign = Image("{{assets}}/bg/field-sign.png")
image bg field = Image("{{assets}}/bg/field.png")
image bg forest = Image("{{assets}}/bg/forest.png")
image bg Galekh_Study_Int = Image("{{assets}}/bg/Galekh_Study_Int.png")
image bg greenroom-dark = Image("{{assets}}/bg/greenroom-dark.png")
image bg greenroom-light = Image("{{assets}}/bg/greenroom-light.png")
image bg hallway_blood = Image("{{assets}}/bg/hallway_blood.png")
image bg hallway_final = Image("{{assets}}/bg/hallway_final.png")
image bg hole_dark = Image("{{assets}}/bg/hole_dark.png")
image bg hole_light = Image("{{assets}}/bg/hole_light.png")
image bg houseext_final = Image("{{assets}}/bg/houseext_final.png")
image bg junkyard_bw = Image("{{assets}}/bg/junkyard_bw.png")
image bg junkyard_final = Image("{{assets}}/bg/junkyard_final.png")
image bg kitchen = Image("{{assets}}/bg/kitchen.png")
image bg Konyyl_spaceship1 = Image("{{assets}}/bg/Konyyl_spaceship1.png")
image bg Konyyl_spaceship2 = Image("{{assets}}/bg/Konyyl_spaceship2.png")
image bg Konyyl_warehouse_exterior = Image("{{assets}}/bg/Konyyl_warehouse_exterior.png")
image bg Konyyl_warehouse_interior = Image("{{assets}}/bg/Konyyl_warehouse_interior.png")
image bg limo = Image("{{assets}}/bg/limo.png")
image bg limo2 = Image("{{assets}}/bg/limo2.png")
image bg living room = Image("{{assets}}/bg/living room.png")
image bg loft = Image("{{assets}}/bg/loft.png")
image bg mall3 = Image("{{assets}}/bg/mall3.png")
image bg meat_locker = Image("{{assets}}/bg/meat_locker.png")
image bg neighborhood3 = Image("{{assets}}/bg/neighborhood3.png")
image bg neighborhood_rain_final = Image("{{assets}}/bg/neighborhood_rain_final.png")
image bg otakushop = Image("{{assets}}/bg/otakushop.png")
image bg party = Image("{{assets}}/bg/party.png")
image bg party_kitchen = Image("{{assets}}/bg/party_kitchen.png")
image bg party_poetry reading = Image("{{assets}}/bg/party_poetry reading.png")
image bg polypa_apartment = Image("{{assets}}/bg/polypa_apartment.png")
image bg polypa_theater = Image("{{assets}}/bg/polypa_theater.png")
image bg Remele_gallery = Image("{{assets}}/bg/Remele_gallery.png")
image bg Remele_museum1 = Image("{{assets}}/bg/Remele_museum1.png")
image bg Remele_museum2 = Image("{{assets}}/bg/Remele_museum2.png")
image bg Remele_museum3 = Image("{{assets}}/bg/Remele_museum3.png")
image bg renfaire_final = Image("{{assets}}/bg/renfaire_final.png")
image bg respiteblock = Image("{{assets}}/bg/respiteblock.png")
image bg river_final = Image("{{assets}}/bg/river_final.png")
image bg room1_final = Image("{{assets}}/bg/room1_final.png")
image bg room2_dim = Image("{{assets}}/bg/room2_dim.png")
image bg room2_normal = Image("{{assets}}/bg/room2_normal.png")
image bg room2_spotlight = Image("{{assets}}/bg/room2_spotlight.png")
image bg scratch endcard = Image("{{assets}}/bg/scratch endcard.png")
image bg scratch_computer = Image("{{assets}}/bg/scratch_computer.png")
image bg scratch_room = Image("{{assets}}/bg/scratch_room.png")
image bg scuttlebuggyint_final = Image("{{assets}}/bg/scuttlebuggyint_final.png")
image bg sewer = Image("{{assets}}/bg/sewer.png")
image bg shops3 = Image("{{assets}}/bg/shops3.png")
image bg skylla_hive = Image("{{assets}}/bg/skylla_hive.png")
image bg stage = Image("{{assets}}/bg/stage.png")
image bg stelsa_office_final = Image("{{assets}}/bg/stelsa_office_final.png")
image bg stelsa_respite_final = Image("{{assets}}/bg/stelsa_respite_final.png")
image bg street = Image("{{assets}}/bg/street.png")
image bg tagorabath = Image("{{assets}}/bg/tagorabath.png")
image bg tagoraexterior = Image("{{assets}}/bg/tagoraexterior.png")
image bg tagorainterior = Image("{{assets}}/bg/tagorainterior.png")
image bg tegirihive = Image("{{assets}}/bg/tegirihive.png")
image bg teg_hive_done = Image("{{assets}}/bg/teg_hive_done.png")
image bg Tirona_Jail_Cell = Image("{{assets}}/bg/Tirona_Jail_Cell.png")
image bg Tirona_Law_Office_Tagora = Image("{{assets}}/bg/Tirona_Law_Office_Tagora.png")
image bg Tirona_Law_Office_Tirona = Image("{{assets}}/bg/Tirona_Law_Office_Tirona.png")
image bg Tirona_Law_Office_Tyzias = Image("{{assets}}/bg/Tirona_Law_Office_Tyzias.png")
image bg torture = Image("{{assets}}/bg/torture.png")
image bg Trainstation = Image("{{assets}}/bg/Trainstation.png")
image bg tyzias_bookhive = Image("{{assets}}/bg/tyzias_bookhive.png")
image bg tyzias_townoutskirts = Image("{{assets}}/bg/tyzias_townoutskirts.png")
image bg vikareblock = Image("{{assets}}/bg/vikareblock.png")
image bg vikarehive = Image("{{assets}}/bg/vikarehive.png")
image bg waterway = Image("{{assets}}/bg/waterway.png")
image bg workout2 = Image("{{assets}}/bg/workout2.png")
image bg yourhive = Image("{{assets}}/bg/yourhive.png")
image bg zebedehive = Image("{{assets}}/bg/zebedehive.png")
image bg zebedehiveinterior = Image("{{assets}}/bg/zebedehiveinterior.png")
image bg zebruh_concert = Image("{{assets}}/bg/zebruh_concert.png")
image bg zebruh_mansion = Image("{{assets}}/bg/zebruh_mansion.png")
image bg zen_garden = Image("{{assets}}/bg/zen_garden.png")

# ../custom_volumes_other/hiveswap\BAIZLI.rpy
define baizli = Character(name="BAIZLI", kind=hiveswap, image="baizli", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image baizli CalmManic = Image("{{assets}}/sprite/BAIZLI_CalmManic.png", ypos=730)
image baizli CalmManicTalk = Image("{{assets}}/sprite/BAIZLI_CalmManicTalk.png", ypos=730)
image baizli CalmMorose = Image("{{assets}}/sprite/BAIZLI_CalmMorose.png", ypos=730)
image baizli CalmMoroseTalk = Image("{{assets}}/sprite/BAIZLI_CalmMoroseTalk.png", ypos=730)
image baizli Confused = Image("{{assets}}/sprite/BAIZLI_Confused.png", ypos=730)
image baizli ConfusedTalking = Image("{{assets}}/sprite/BAIZLI_ConfusedTalking.png", ypos=730)
image baizli Disapproving = Image("{{assets}}/sprite/BAIZLI_Disapproving.png", ypos=730)
image baizli DisapprovingTalk = Image("{{assets}}/sprite/BAIZLI_DisapprovingTalk.png", ypos=730)
image baizli InShadow = Image("{{assets}}/sprite/BAIZLI_InShadow.png", ypos=730)
image baizli Laughing = Image("{{assets}}/sprite/BAIZLI_Laughing.png", ypos=730)
image baizli Neutral = Image("{{assets}}/sprite/BAIZLI_Neutral.png", ypos=730)
image baizli NeutralTalking = Image("{{assets}}/sprite/BAIZLI_NeutralTalking.png", ypos=730)
image baizli Skeptical = Image("{{assets}}/sprite/BAIZLI_Skeptical.png", ypos=730)
image baizli Thinking = Image("{{assets}}/sprite/BAIZLI_Thinking.png", ypos=730)
image baizli ThinkingTalk = Image("{{assets}}/sprite/BAIZLI_ThinkingTalk.png", ypos=730)

# ../custom_volumes_other/hiveswap\BARZUM.rpy
define barzum = Character(name="BARZUM", kind=hiveswap, image="barzum", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image barzum CalmManic = Image("{{assets}}/sprite/BARZUM_CalmManic.png", ypos=730)
image barzum CalmManicTalk = Image("{{assets}}/sprite/BARZUM_CalmManicTalk.png", ypos=730)
image barzum CalmMorose = Image("{{assets}}/sprite/BARZUM_CalmMorose.png", ypos=730)
image barzum CalmMoroseTalk = Image("{{assets}}/sprite/BARZUM_CalmMoroseTalk.png", ypos=730)
image barzum Confused = Image("{{assets}}/sprite/BARZUM_Confused.png", ypos=730)
image barzum ConfusedTalk = Image("{{assets}}/sprite/BARZUM_ConfusedTalk.png", ypos=730)
image barzum Disapproving = Image("{{assets}}/sprite/BARZUM_Disapproving.png", ypos=730)
image barzum DisapprovingTalk = Image("{{assets}}/sprite/BARZUM_DisapprovingTalk.png", ypos=730)
image barzum InShadow = Image("{{assets}}/sprite/BARZUM_InShadow.png", ypos=730)
image barzum Laughing = Image("{{assets}}/sprite/BARZUM_Laughing.png", ypos=730)
image barzum Neutral = Image("{{assets}}/sprite/BARZUM_Neutral.png", ypos=730)
image barzum NeutralTalk = Image("{{assets}}/sprite/BARZUM_NeutralTalk.png", ypos=730)
image barzum Sketpical = Image("{{assets}}/sprite/BARZUM_Sketpical.png", ypos=730)
image barzum Thinking = Image("{{assets}}/sprite/BARZUM_Thinking.png", ypos=730)
image barzum ThinkingTalk = Image("{{assets}}/sprite/BARZUM_ThinkingTalk.png", ypos=730)

# ../custom_volumes_other/hiveswap\boldir.rpy
define boldir = Character(name="BOLDIR", kind=hiveswap, image="boldir", window_background="gui/textbox_olive.png", who_outlines=[(4, "#416600")])

image boldir antidote = Image("{{assets}}/sprite/boldir_antidote.png", ypos=730)
image boldir cold = Image("{{assets}}/sprite/boldir_cold.png", ypos=730)
image boldir cold_small = Image("{{assets}}/sprite/boldir_cold_small.png", ypos=730)
image boldir dressneutral = Image("{{assets}}/sprite/boldir_dressneutral.png", ypos=730)
image boldir dressthoughtful = Image("{{assets}}/sprite/boldir_dressthoughtful.png", ypos=730)
image boldir dresswideeyed = Image("{{assets}}/sprite/boldir_dresswideeyed.png", ypos=730)
image boldir dying = Image("{{assets}}/sprite/boldir_dying.png", ypos=730)
image boldir hurt = Image("{{assets}}/sprite/boldir_hurt.png", ypos=730)
image boldir mean = Image("{{assets}}/sprite/boldir_mean.png", ypos=730)
image boldir mean_small = Image("{{assets}}/sprite/boldir_mean_small.png", ypos=730)
image boldir neutral = Image("{{assets}}/sprite/boldir_neutral.png", ypos=730)
image boldir oof = Image("{{assets}}/sprite/boldir_oof.png", ypos=730)
image boldir thoughtful = Image("{{assets}}/sprite/boldir_thoughtful.png", ypos=730)
image boldir wideeyed = Image("{{assets}}/sprite/boldir_wideeyed.png", ypos=730)

# ../custom_volumes_other/hiveswap\bronya.rpy
define bronya = Character(name="BRONYA", kind=hiveswap, image="bronya", window_background="gui/textbox_jade.png", who_outlines=[(4, "#0aa85b")])

image bronya angry = Image("{{assets}}/sprite/bronya_angry.png", ypos=730)
image bronya duty = Image("{{assets}}/sprite/bronya_duty.png", ypos=730)
image bronya happy = Image("{{assets}}/sprite/bronya_happy.png", ypos=730)
image bronya motherly = Image("{{assets}}/sprite/bronya_motherly.png", ypos=730)
image bronya panic = Image("{{assets}}/sprite/bronya_panic.png", ypos=730)
image bronya talk = Image("{{assets}}/sprite/bronya_talk.png", ypos=730)
image bronya umm = Image("{{assets}}/sprite/bronya_umm.png", ypos=730)
image bronya worried = Image("{{assets}}/sprite/bronya_worried.png", ypos=730)

# ../custom_volumes_other/hiveswap\Chahut.rpy
define chahut = Character(name="CHAHUT", kind=hiveswap, image="chahut", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image chahut blood = Image("{{assets}}/sprite/Chahut_blood.png", ypos=730)
image chahut lazysmile = Image("{{assets}}/sprite/Chahut_lazysmile.png", ypos=730)
image chahut neutral = Image("{{assets}}/sprite/Chahut_neutral.png", ypos=730)
image chahut pissed = Image("{{assets}}/sprite/Chahut_pissed.png", ypos=730)
image chahut pray = Image("{{assets}}/sprite/Chahut_pray.png", ypos=730)
image chahut spray = Image("{{assets}}/sprite/Chahut_spray.png", ypos=730)
image chahut suprise = Image("{{assets}}/sprite/Chahut_suprise.png", ypos=730)
image chahut wince = Image("{{assets}}/sprite/Chahut_wince.png", ypos=730)

# ../custom_volumes_other/hiveswap\charun.rpy
define charun = Character(name="CHARUN", kind=hiveswap, image="charun", window_background="gui/textbox_olive.png", who_outlines=[(4, "#416600")])

image charun allartisdickingaround = Image("{{assets}}/sprite/charun_allartisdickingaround.png", ypos=730)
image charun bandannaneutral = Image("{{assets}}/sprite/charun_bandannaneutral.png", ypos=730)
image charun bandannaseeanything = Image("{{assets}}/sprite/charun_bandannaseeanything.png", ypos=730)
image charun bandannasquint = Image("{{assets}}/sprite/charun_bandannasquint.png", ypos=730)
image charun canihaveit = Image("{{assets}}/sprite/charun_canihaveit.png", ypos=730)
image charun disappointed = Image("{{assets}}/sprite/charun_disappointed.png", ypos=730)
image charun itsbeautiful = Image("{{assets}}/sprite/charun_itsbeautiful.png", ypos=730)
image charun maybe = Image("{{assets}}/sprite/charun_maybe.png", ypos=730)
image charun neutral_imstuck = Image("{{assets}}/sprite/charun_neutral_imstuck.png", ypos=730)
image charun pleased = Image("{{assets}}/sprite/charun_pleased.png", ypos=730)
image charun quoteinteresting = Image("{{assets}}/sprite/charun_quoteinteresting.png", ypos=730)
image charun squint = Image("{{assets}}/sprite/charun_squint.png", ypos=730)
image charun thereis = Image("{{assets}}/sprite/charun_thereis.png", ypos=730)
image charun tired = Image("{{assets}}/sprite/charun_tired.png", ypos=730)

# ../custom_volumes_other/hiveswap\Chixie.rpy
define chixie = Character(name="CHIXIE", kind=hiveswap, image="chixie", window_background="gui/textbox_bronze.png", who_outlines=[(4, "#bb6405")])

image chixie annoyed = Image("{{assets}}/sprite/Chixie_annoyed.png", ypos=730)
image chixie crying = Image("{{assets}}/sprite/Chixie_crying.png", ypos=730)
image chixie customerserviceface = Image("{{assets}}/sprite/Chixie_customerserviceface.png", ypos=730)
image chixie dejected = Image("{{assets}}/sprite/Chixie_dejected.png", ypos=730)
image chixie frown = Image("{{assets}}/sprite/Chixie_frown.png", ypos=730)
image chixie happy = Image("{{assets}}/sprite/Chixie_happy.png", ypos=730)
image chixie mad = Image("{{assets}}/sprite/Chixie_mad.png", ypos=730)
image chixie nervous = Image("{{assets}}/sprite/Chixie_nervous.png", ypos=730)
image chixie neutral = Image("{{assets}}/sprite/Chixie_neutral.png", ypos=730)
image chixie ouch = Image("{{assets}}/sprite/Chixie_ouch.png", ypos=730)
image chixie pissed = Image("{{assets}}/sprite/Chixie_pissed.png", ypos=730)
image chixie RAP = Image("{{assets}}/sprite/Chixie_RAP.png", ypos=730)
image chixie sad = Image("{{assets}}/sprite/Chixie_sad.png", ypos=730)
image chixie sadfaygo = Image("{{assets}}/sprite/Chixie_sadfaygo.png", ypos=730)
image chixie shocked = Image("{{assets}}/sprite/Chixie_shocked.png", ypos=730)
image chixie talk = Image("{{assets}}/sprite/Chixie_talk.png", ypos=730)

# ../custom_volumes_other/hiveswap\cirava.rpy
define cirava = Character(name="CIRAVA", kind=hiveswap, image="cirava", window_background="gui/textbox_gold.png", who_outlines=[(4, "#a1a100")])

image cirava angst = Image("{{assets}}/sprite/cirava_angst.png", ypos=730)
image cirava cross = Image("{{assets}}/sprite/cirava_cross.png", ypos=730)
image cirava feelingit = Image("{{assets}}/sprite/cirava_feelingit.png", ypos=730)
image cirava peace = Image("{{assets}}/sprite/cirava_peace.png", ypos=730)
image cirava point = Image("{{assets}}/sprite/cirava_point.png", ypos=730)
image cirava shrug = Image("{{assets}}/sprite/cirava_shrug.png", ypos=730)
image cirava standing = Image("{{assets}}/sprite/cirava_standing.png", ypos=730)
image cirava talk = Image("{{assets}}/sprite/cirava_talk.png", ypos=730)
image cirava vape = Image("{{assets}}/sprite/cirava_vape.png", ypos=730)

# ../custom_volumes_other/hiveswap\daraya.rpy
define daraya = Character(name="DARAYA", kind=hiveswap, image="daraya", window_background="gui/textbox_jade.png", who_outlines=[(4, "#0aa85b")])

image daraya burnitdown = Image("{{assets}}/sprite/daraya_burnitdown.png", ypos=730)
image daraya comeon = Image("{{assets}}/sprite/daraya_comeon.png", ypos=730)
image daraya elwurdspcool = Image("{{assets}}/sprite/daraya_elwurdspcool.png", ypos=730)
image daraya eyeroll = Image("{{assets}}/sprite/daraya_eyeroll.png", ypos=730)
image daraya frozen = Image("{{assets}}/sprite/daraya_frozen.png", ypos=730)
image daraya frustrated = Image("{{assets}}/sprite/daraya_frustrated.png", ypos=730)
image daraya gross = Image("{{assets}}/sprite/daraya_gross.png", ypos=730)
image daraya oldbuildingsarekindasick = Image("{{assets}}/sprite/daraya_oldbuildingsarekindasick.png", ypos=730)
image daraya quirkedup = Image("{{assets}}/sprite/daraya_quirkedup.png", ypos=730)
image daraya sogoodriddance = Image("{{assets}}/sprite/daraya_sogoodriddance.png", ypos=730)
image daraya takemewithyou = Image("{{assets}}/sprite/daraya_takemewithyou.png", ypos=730)
image daraya trapped = Image("{{assets}}/sprite/daraya_trapped.png", ypos=730)
image daraya ughitsyou = Image("{{assets}}/sprite/daraya_ughitsyou.png", ypos=730)
image daraya uhhyouknowwhat = Image("{{assets}}/sprite/daraya_uhhyouknowwhat.png", ypos=730)
image daraya upset = Image("{{assets}}/sprite/daraya_upset.png", ypos=730)
image daraya well = Image("{{assets}}/sprite/daraya_well.png", ypos=730)
image daraya whatever = Image("{{assets}}/sprite/daraya_whatever.png", ypos=730)
image daraya WHOCARES = Image("{{assets}}/sprite/daraya_WHOCARES.png", ypos=730)

# ../custom_volumes_other/hiveswap\diemen.rpy
define diemen = Character(name="DIEMEN", kind=hiveswap, image="diemen", window_background="gui/textbox_rust.png", who_outlines=[(4, "#a20000")])

image diemen cry = Image("{{assets}}/sprite/diemen_cry.png", ypos=730)
image diemen cry_dogless = Image("{{assets}}/sprite/diemen_cry_dogless.png", ypos=730)
image diemen cry_shirtless = Image("{{assets}}/sprite/diemen_cry_shirtless.png", ypos=730)
image diemen curious = Image("{{assets}}/sprite/diemen_curious.png", ypos=730)
image diemen curious_dogless = Image("{{assets}}/sprite/diemen_curious_dogless.png", ypos=730)
image diemen curious_shirtless = Image("{{assets}}/sprite/diemen_curious_shirtless.png", ypos=730)
image diemen die_shirtless = Image("{{assets}}/sprite/diemen_die_shirtless.png", ypos=730)
image diemen frown = Image("{{assets}}/sprite/diemen_frown.png", ypos=730)
image diemen frown_dogless = Image("{{assets}}/sprite/diemen_frown_dogless.png", ypos=730)
image diemen offer = Image("{{assets}}/sprite/diemen_offer.png", ypos=730)
image diemen offer_dogless = Image("{{assets}}/sprite/diemen_offer_dogless.png", ypos=730)
image diemen offer_dogless_resized = Image("{{assets}}/sprite/diemen_offer_dogless_resized.png", ypos=730)
image diemen offer_shirtless = Image("{{assets}}/sprite/diemen_offer_shirtless.png", ypos=730)
image diemen optimistic = Image("{{assets}}/sprite/diemen_optimistic.png", ypos=730)
image diemen optimistic_dogless = Image("{{assets}}/sprite/diemen_optimistic_dogless.png", ypos=730)
image diemen optimistic_dogless_resized = Image("{{assets}}/sprite/diemen_optimistic_dogless_resized.png", ypos=730)
image diemen optimistic_scaled = Image("{{assets}}/sprite/diemen_optimistic_scaled.png", ypos=730)
image diemen recoil = Image("{{assets}}/sprite/diemen_recoil.png", ypos=730)
image diemen recoil_shirtless = Image("{{assets}}/sprite/diemen_recoil_shirtless.png", ypos=730)
image diemen shock = Image("{{assets}}/sprite/diemen_shock.png", ypos=730)
image diemen shock_shirtless = Image("{{assets}}/sprite/diemen_shock_shirtless.png", ypos=730)
image diemen smile = Image("{{assets}}/sprite/diemen_smile.png", ypos=730)
image diemen smile_dogless = Image("{{assets}}/sprite/diemen_smile_dogless.png", ypos=730)
image diemen smile_dogless_resized = Image("{{assets}}/sprite/diemen_smile_dogless_resized.png", ypos=730)
image diemen smile_scaled = Image("{{assets}}/sprite/diemen_smile_scaled.png", ypos=730)
image diemen smile_shirtless = Image("{{assets}}/sprite/diemen_smile_shirtless.png", ypos=730)
image diemen talk = Image("{{assets}}/sprite/diemen_talk.png", ypos=730)
image diemen talk_dogless = Image("{{assets}}/sprite/diemen_talk_dogless.png", ypos=730)
image diemen talk_dogless_resized = Image("{{assets}}/sprite/diemen_talk_dogless_resized.png", ypos=730)
image diemen thinking = Image("{{assets}}/sprite/diemen_thinking.png", ypos=730)
image diemen thinking_dogless = Image("{{assets}}/sprite/diemen_thinking_dogless.png", ypos=730)
image diemen thinking_dogless_resized = Image("{{assets}}/sprite/diemen_thinking_dogless_resized.png", ypos=730)

init python:
    quirks["diemen"] = [("(.+)", "(| \g<1> |)")]

# ../custom_volumes_other/hiveswap\DS.rpy

# ../custom_volumes_other/hiveswap\effects.rpy
image fx bgbison = Image("{{assets}}/object/bgbison.png")
image fx bisonlusus = Image("{{assets}}/object/bisonlusus.png")
image fx bush = Image("{{assets}}/object/bush.png")
image fx bush_orig = Image("{{assets}}/object/bush_orig.png")
image fx cholerbear = Image("{{assets}}/object/cholerbear.png")
image fx cholerbearhires = Image("{{assets}}/object/cholerbearhires.png")
image fx ferret_lusus = Image("{{assets}}/object/ferret_lusus.png")
image fx hatched2dance = Image("{{assets}}/object/hatched2dance.png")
image fx hors = Image("{{assets}}/object/hors.png")
image fx lady = Image("{{assets}}/object/lady.png")
image fx NIHKEEBORG = Image("{{assets}}/object/NIHKEEBORG.png")
image fx shibasaru = Image("{{assets}}/object/shibasaru.png")
image fx statue = Image("{{assets}}/object/statue.png")
image fx tegirijojo = Image("{{assets}}/object/tegirijojo.png")
image fx zebralusus = Image("{{assets}}/object/zebralusus.png")

# ../custom_volumes_other/hiveswap\elwurd.rpy
define elwurd = Character(name="ELWURD", kind=hiveswap, image="elwurd", window_background="gui/textbox_cobalt.png", who_outlines=[(4, "#005682")])

image elwurd casualsurprise = Image("{{assets}}/sprite/elwurd_casualsurprise.png", ypos=730)
image elwurd defensive = Image("{{assets}}/sprite/elwurd_defensive.png", ypos=730)
image elwurd fingerguns = Image("{{assets}}/sprite/elwurd_fingerguns.png", ypos=730)
image elwurd frown = Image("{{assets}}/sprite/elwurd_frown.png", ypos=730)
image elwurd handsome = Image("{{assets}}/sprite/elwurd_handsome.png", ypos=730)
image elwurd headtilt = Image("{{assets}}/sprite/elwurd_headtilt.png", ypos=730)
image elwurd interested = Image("{{assets}}/sprite/elwurd_interested.png", ypos=730)
image elwurd pissed = Image("{{assets}}/sprite/elwurd_pissed.png", ypos=730)
image elwurd psh = Image("{{assets}}/sprite/elwurd_psh.png", ypos=730)
image elwurd scowl = Image("{{assets}}/sprite/elwurd_scowl.png", ypos=730)
image elwurd shrug = Image("{{assets}}/sprite/elwurd_shrug.png", ypos=730)
image elwurd smile = Image("{{assets}}/sprite/elwurd_smile.png", ypos=730)
image elwurd ugh = Image("{{assets}}/sprite/elwurd_ugh.png", ypos=730)

# ../custom_volumes_other/hiveswap\ferret.rpy

# ../custom_volumes_other/hiveswap\folykl.rpy
define folykl = Character(name="FOLYKL", kind=hiveswap, image="folykl", window_background="gui/textbox_gold.png", who_outlines=[(4, "#a1a100")])

image folykl idle = Image("{{assets}}/sprite/folykl_idle.png", ypos=730)
image folykl pain = Image("{{assets}}/sprite/folykl_pain.png", ypos=730)
image folykl scaled = Image("{{assets}}/sprite/folykl_scaled.png", ypos=730)

# ../custom_volumes_other/hiveswap\FOLYKLKUPRUM.rpy
define folyklkuprum = Character(name="FOLYKLKUPRUM", kind=hiveswap, image="folyklkuprum", window_background="gui/textbox_gold.png", who_outlines=[(4, "#a1a100")])

image folyklkuprum double frown = Image("{{assets}}/sprite/FOLYKLKUPRUM_double frown.png", ypos=730)
image folyklkuprum doublegrin = Image("{{assets}}/sprite/FOLYKLKUPRUM_doublegrin.png", ypos=730)
image folyklkuprum f_mouthopen = Image("{{assets}}/sprite/FOLYKLKUPRUM_f_mouthopen.png", ypos=730)
image folyklkuprum grin = Image("{{assets}}/sprite/FOLYKLKUPRUM_grin.png", ypos=730)
image folyklkuprum hairtug = Image("{{assets}}/sprite/FOLYKLKUPRUM_hairtug.png", ypos=730)
image folyklkuprum hairtug_angry = Image("{{assets}}/sprite/FOLYKLKUPRUM_hairtug_angry.png", ypos=730)
image folyklkuprum karmsdown = Image("{{assets}}/sprite/FOLYKLKUPRUM_karmsdown.png", ypos=730)
image folyklkuprum k_armpower = Image("{{assets}}/sprite/FOLYKLKUPRUM_k_armpower.png", ypos=730)
image folyklkuprum k_mouthopen = Image("{{assets}}/sprite/FOLYKLKUPRUM_k_mouthopen.png", ypos=730)
image folyklkuprum POWER = Image("{{assets}}/sprite/FOLYKLKUPRUM_POWER.png", ypos=730)

# ../custom_volumes_other/hiveswap\fozzer.rpy
define fozzer = Character(name="FOZZER", kind=hiveswap, image="fozzer", window_background="gui/textbox_rust.png", who_outlines=[(4, "#a20000")])

image fozzer accusatory = Image("{{assets}}/sprite/fozzer_accusatory.png", ypos=730)
image fozzer AirQuotes = Image("{{assets}}/sprite/fozzer_AirQuotes.png", ypos=730)
image fozzer ArmsCrossed = Image("{{assets}}/sprite/fozzer_ArmsCrossed.png", ypos=730)
image fozzer ArmsCrossedDispleased = Image("{{assets}}/sprite/fozzer_ArmsCrossedDispleased.png", ypos=730)
image fozzer ArmsCrossedQuestioning = Image("{{assets}}/sprite/fozzer_ArmsCrossedQuestioning.png", ypos=730)
image fozzer digging = Image("{{assets}}/sprite/fozzer_digging.png", ypos=730)
image fozzer embrace = Image("{{assets}}/sprite/fozzer_embrace.png", ypos=730)
image fozzer estatic = Image("{{assets}}/sprite/fozzer_estatic.png", ypos=730)
image fozzer estaticListening = Image("{{assets}}/sprite/fozzer_estaticListening.png", ypos=730)
image fozzer fistpump = Image("{{assets}}/sprite/fozzer_fistpump.png", ypos=730)
image fozzer LetsShovel = Image("{{assets}}/sprite/fozzer_LetsShovel.png", ypos=730)
image fozzer panicked = Image("{{assets}}/sprite/fozzer_panicked.png", ypos=730)
image fozzer SPOOKED = Image("{{assets}}/sprite/fozzer_SPOOKED.png", ypos=730)
image fozzer squint = Image("{{assets}}/sprite/fozzer_squint.png", ypos=730)
image fozzer thinking = Image("{{assets}}/sprite/fozzer_thinking.png", ypos=730)
image fozzer thinkinghard = Image("{{assets}}/sprite/fozzer_thinkinghard.png", ypos=730)
image fozzer thinkingImpressed = Image("{{assets}}/sprite/fozzer_thinkingImpressed.png", ypos=730)
image fozzer thinkingUnimpressed = Image("{{assets}}/sprite/fozzer_thinkingUnimpressed.png", ypos=730)

# ../custom_volumes_other/hiveswap\galekh.rpy
define galekh = Character(name="GALEKH", kind=hiveswap, image="galekh", window_background="gui/textbox_blue.png", who_outlines=[(4, "#000056")])

image galekh disappointedpause = Image("{{assets}}/sprite/galekh_disappointedpause.png", ypos=730)
image galekh expressions001 = Image("{{assets}}/sprite/galekh_expressions001.png", ypos=730)
image galekh frustration = Image("{{assets}}/sprite/galekh_frustration.png", ypos=730)
image galekh glare = Image("{{assets}}/sprite/galekh_glare.png", ypos=730)
image galekh neutral = Image("{{assets}}/sprite/galekh_neutral.png", ypos=730)
image galekh nojacketneutral = Image("{{assets}}/sprite/galekh_nojacketneutral.png", ypos=730)
image galekh nojacketpleased = Image("{{assets}}/sprite/galekh_nojacketpleased.png", ypos=730)
image galekh pissed = Image("{{assets}}/sprite/galekh_pissed.png", ypos=730)
image galekh pleased = Image("{{assets}}/sprite/galekh_pleased.png", ypos=730)
image galekh questioning = Image("{{assets}}/sprite/galekh_questioning.png", ypos=730)
image galekh surprise = Image("{{assets}}/sprite/galekh_surprise.png", ypos=730)
image galekh tattoocrookedsmile = Image("{{assets}}/sprite/galekh_tattoocrookedsmile.png", ypos=730)
image galekh tattooflush = Image("{{assets}}/sprite/galekh_tattooflush.png", ypos=730)
image galekh tattooneutral = Image("{{assets}}/sprite/galekh_tattooneutral.png", ypos=730)
image galekh tattoowince = Image("{{assets}}/sprite/galekh_tattoowince.png", ypos=730)

# ../custom_volumes_other/hiveswap\Karako.rpy
define karako = Character(name="KARAKO", kind=hiveswap, image="karako", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image karako ATTACK = Image("{{assets}}/sprite/Karako_ATTACK.png", ypos=730)
image karako curious = Image("{{assets}}/sprite/Karako_curious.png", ypos=730)
image karako emo = Image("{{assets}}/sprite/Karako_emo.png", ypos=730)
image karako FEAR = Image("{{assets}}/sprite/Karako_FEAR.png", ypos=730)
image karako grateful = Image("{{assets}}/sprite/Karako_grateful.png", ypos=730)
image karako happy = Image("{{assets}}/sprite/Karako_happy.png", ypos=730)
image karako injured = Image("{{assets}}/sprite/Karako_injured.png", ypos=730)
image karako RLYupset = Image("{{assets}}/sprite/Karako_RLYupset.png", ypos=730)
image karako treestuck = Image("{{assets}}/sprite/Karako_treestuck.png", ypos=730)
image karako upset = Image("{{assets}}/sprite/Karako_upset.png", ypos=730)

# ../custom_volumes_other/hiveswap\Konyyl.rpy
define konyyl = Character(name="KONYYL", kind=hiveswap, image="konyyl", window_background="gui/textbox_olive.png", who_outlines=[(4, "#416600")])

image konyyl ask = Image("{{assets}}/sprite/Konyyl_ask.png", ypos=730)
image konyyl attack = Image("{{assets}}/sprite/Konyyl_attack.png", ypos=730)
image konyyl defeated = Image("{{assets}}/sprite/Konyyl_defeated.png", ypos=730)
image konyyl laugh = Image("{{assets}}/sprite/Konyyl_laugh.png", ypos=730)
image konyyl menacing = Image("{{assets}}/sprite/Konyyl_menacing.png", ypos=730)
image konyyl neutral = Image("{{assets}}/sprite/Konyyl_neutral.png", ypos=730)
image konyyl sad = Image("{{assets}}/sprite/Konyyl_sad.png", ypos=730)
image konyyl surprised = Image("{{assets}}/sprite/Konyyl_surprised.png", ypos=730)
image konyyl thinking = Image("{{assets}}/sprite/Konyyl_thinking.png", ypos=730)
image konyyl why = Image("{{assets}}/sprite/Konyyl_why.png", ypos=730)

# ../custom_volumes_other/hiveswap\kuprum.rpy
define kuprum = Character(name="KUPRUM", kind=hiveswap, image="kuprum", window_background="gui/textbox_gold.png", who_outlines=[(4, "#a1a100")])

image kuprum anger = Image("{{assets}}/sprite/kuprum_anger.png", ypos=730)
image kuprum idle = Image("{{assets}}/sprite/kuprum_idle.png", ypos=730)
image kuprum POWER = Image("{{assets}}/sprite/kuprum_POWER.png", ypos=730)

# ../custom_volumes_other/hiveswap\LANQUE.rpy
define lanque = Character(name="LANQUE", kind=hiveswap, image="lanque", window_background="gui/textbox_jade.png", who_outlines=[(4, "#0aa85b")])

image lanque Bitching = Image("{{assets}}/sprite/LANQUE_Bitching.png", ypos=730)
image lanque Close = Image("{{assets}}/sprite/LANQUE_Close.png", ypos=730)
image lanque CloseHiding = Image("{{assets}}/sprite/LANQUE_CloseHiding.png", ypos=730)
image lanque CloseJK = Image("{{assets}}/sprite/LANQUE_CloseJK.png", ypos=730)
image lanque CloseKiss = Image("{{assets}}/sprite/LANQUE_CloseKiss.png", ypos=730)
image lanque CloseLicky = Image("{{assets}}/sprite/LANQUE_CloseLicky.png", ypos=730)
image lanque CloseNakeyKiss = Image("{{assets}}/sprite/LANQUE_CloseNakeyKiss.png", ypos=730)
image lanque CloseNakeyShh = Image("{{assets}}/sprite/LANQUE_CloseNakeyShh.png", ypos=730)
image lanque CloseNakeyTalk = Image("{{assets}}/sprite/LANQUE_CloseNakeyTalk.png", ypos=730)
image lanque CloseTalk = Image("{{assets}}/sprite/LANQUE_CloseTalk.png", ypos=730)
image lanque Embrace = Image("{{assets}}/sprite/LANQUE_Embrace.png", ypos=730)
image lanque Grinding = Image("{{assets}}/sprite/LANQUE_Grinding.png", ypos=730)
image lanque Hmph = Image("{{assets}}/sprite/LANQUE_Hmph.png", ypos=730)
image lanque Interesting = Image("{{assets}}/sprite/LANQUE_Interesting.png", ypos=730)
image lanque InterestingTalk = Image("{{assets}}/sprite/LANQUE_InterestingTalk.png", ypos=730)
image lanque Laughing = Image("{{assets}}/sprite/LANQUE_Laughing.png", ypos=730)
image lanque Licky = Image("{{assets}}/sprite/LANQUE_Licky.png", ypos=730)
image lanque NakeyBitching = Image("{{assets}}/sprite/LANQUE_NakeyBitching.png", ypos=730)
image lanque NakeyFeigning = Image("{{assets}}/sprite/LANQUE_NakeyFeigning.png", ypos=730)
image lanque NakeyHmph = Image("{{assets}}/sprite/LANQUE_NakeyHmph.png", ypos=730)
image lanque NakeyOhShit = Image("{{assets}}/sprite/LANQUE_NakeyOhShit.png", ypos=730)
image lanque NakeySlapped = Image("{{assets}}/sprite/LANQUE_NakeySlapped.png", ypos=730)
image lanque Neutral = Image("{{assets}}/sprite/LANQUE_Neutral.png", ypos=730)
image lanque NeutralTalk = Image("{{assets}}/sprite/LANQUE_NeutralTalk.png", ypos=730)
image lanque OhShit = Image("{{assets}}/sprite/LANQUE_OhShit.png", ypos=730)
image lanque Questioning = Image("{{assets}}/sprite/LANQUE_Questioning.png", ypos=730)
image lanque Redress = Image("{{assets}}/sprite/LANQUE_Redress.png", ypos=730)
image lanque RedressExcuses = Image("{{assets}}/sprite/LANQUE_RedressExcuses.png", ypos=730)
image lanque Scathing = Image("{{assets}}/sprite/LANQUE_Scathing.png", ypos=730)
image lanque Smile = Image("{{assets}}/sprite/LANQUE_Smile.png", ypos=730)
image lanque Sneer = Image("{{assets}}/sprite/LANQUE_Sneer.png", ypos=730)
image lanque Undress = Image("{{assets}}/sprite/LANQUE_Undress.png", ypos=730)
image lanque VALID_Happy = Image("{{assets}}/sprite/LANQUE_VALID_Happy.png", ypos=730)
image lanque VALID_Heartfelt = Image("{{assets}}/sprite/LANQUE_VALID_Heartfelt.png", ypos=730)
image lanque VALID_HeartfeltTalk = Image("{{assets}}/sprite/LANQUE_VALID_HeartfeltTalk.png", ypos=730)
image lanque VALID_JoinUs = Image("{{assets}}/sprite/LANQUE_VALID_JoinUs.png", ypos=730)
image lanque VALID_Neutral = Image("{{assets}}/sprite/LANQUE_VALID_Neutral.png", ypos=730)
image lanque VALID_PoetryReading = Image("{{assets}}/sprite/LANQUE_VALID_PoetryReading.png", ypos=730)
image lanque VALID_PoetryTears = Image("{{assets}}/sprite/LANQUE_VALID_PoetryTears.png", ypos=730)
image lanque VALID_PoetryTime = Image("{{assets}}/sprite/LANQUE_VALID_PoetryTime.png", ypos=730)
image lanque VALID_PoetryTimeTalk = Image("{{assets}}/sprite/LANQUE_VALID_PoetryTimeTalk.png", ypos=730)
image lanque VALID_Smile = Image("{{assets}}/sprite/LANQUE_VALID_Smile.png", ypos=730)
image lanque VALID_Uh = Image("{{assets}}/sprite/LANQUE_VALID_Uh.png", ypos=730)

# ../custom_volumes_other/hiveswap\lynera.rpy
define lynera = Character(name="LYNERA", kind=hiveswap, image="lynera", window_background="gui/textbox_jade.png", who_outlines=[(4, "#0aa85b")])

image lynera anguish = Image("{{assets}}/sprite/lynera_anguish.png", ypos=730)
image lynera glare = Image("{{assets}}/sprite/lynera_glare.png", ypos=730)
image lynera itsfine = Image("{{assets}}/sprite/lynera_itsfine.png", ypos=730)
image lynera knifethreat = Image("{{assets}}/sprite/lynera_knifethreat.png", ypos=730)
image lynera knifethreattears = Image("{{assets}}/sprite/lynera_knifethreattears.png", ypos=730)
image lynera maybewhatimdoingis = Image("{{assets}}/sprite/lynera_maybewhatimdoingis.png", ypos=730)
image lynera ohnolookwhatyoumademedo = Image("{{assets}}/sprite/lynera_ohnolookwhatyoumademedo.png", ypos=730)
image lynera ohshit = Image("{{assets}}/sprite/lynera_ohshit.png", ypos=730)
image lynera pissed = Image("{{assets}}/sprite/lynera_pissed.png", ypos=730)
image lynera sadredfeelings = Image("{{assets}}/sprite/lynera_sadredfeelings.png", ypos=730)
image lynera smile = Image("{{assets}}/sprite/lynera_smile.png", ypos=730)
image lynera wellinever = Image("{{assets}}/sprite/lynera_wellinever.png", ypos=730)
image lynera whatmoirails = Image("{{assets}}/sprite/lynera_whatmoirails.png", ypos=730)
image lynera wouldyoureally = Image("{{assets}}/sprite/lynera_wouldyoureally.png", ypos=730)
image lynera wrong = Image("{{assets}}/sprite/lynera_wrong.png", ypos=730)

# ../custom_volumes_other/hiveswap\mallek.rpy
define mallek = Character(name="MALLEK", kind=hiveswap, image="mallek", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image mallek down = Image("{{assets}}/sprite/mallek_down.png", ypos=730)
image mallek drones = Image("{{assets}}/sprite/mallek_drones.png", ypos=730)
image mallek grin = Image("{{assets}}/sprite/mallek_grin.png", ypos=730)
image mallek interest = Image("{{assets}}/sprite/mallek_interest.png", ypos=730)
image mallek laugh = Image("{{assets}}/sprite/mallek_laugh.png", ypos=730)
image mallek lowered = Image("{{assets}}/sprite/mallek_lowered.png", ypos=730)
image mallek neutral = Image("{{assets}}/sprite/mallek_neutral.png", ypos=730)
image mallek pissed = Image("{{assets}}/sprite/mallek_pissed.png", ypos=730)
image mallek really = Image("{{assets}}/sprite/mallek_really.png", ypos=730)
image mallek scrutinyannoyance = Image("{{assets}}/sprite/mallek_scrutinyannoyance.png", ypos=730)
image mallek shirtlessflush = Image("{{assets}}/sprite/mallek_shirtlessflush.png", ypos=730)
image mallek shirtlessmybad = Image("{{assets}}/sprite/mallek_shirtlessmybad.png", ypos=730)
image mallek shirtlesstalk = Image("{{assets}}/sprite/mallek_shirtlesstalk.png", ypos=730)
image mallek shirtlessum = Image("{{assets}}/sprite/mallek_shirtlessum.png", ypos=730)

# ../custom_volumes_other/hiveswap\MARSTI.rpy
define marsti = Character(name="MARSTI", kind=hiveswap, image="marsti", window_background="gui/textbox_rust.png", who_outlines=[(4, "#a20000")])

image marsti angry = Image("{{assets}}/sprite/MARSTI_angry.png", ypos=730)
image marsti browquirk = Image("{{assets}}/sprite/MARSTI_browquirk.png", ypos=730)
image marsti browquirk_talking = Image("{{assets}}/sprite/MARSTI_browquirk_talking.png", ypos=730)
image marsti gogglesup = Image("{{assets}}/sprite/MARSTI_gogglesup.png", ypos=730)
image marsti gogglesup_angry = Image("{{assets}}/sprite/MARSTI_gogglesup_angry.png", ypos=730)
image marsti gogglesup_duh = Image("{{assets}}/sprite/MARSTI_gogglesup_duh.png", ypos=730)
image marsti gogglesup_resigned = Image("{{assets}}/sprite/MARSTI_gogglesup_resigned.png", ypos=730)
image marsti gogglesup_snarky = Image("{{assets}}/sprite/MARSTI_gogglesup_snarky.png", ypos=730)
image marsti Neutral = Image("{{assets}}/sprite/MARSTI_Neutral.png", ypos=730)
image marsti Neutral_talking = Image("{{assets}}/sprite/MARSTI_Neutral_talking.png", ypos=730)
image marsti peeved = Image("{{assets}}/sprite/MARSTI_peeved.png", ypos=730)
image marsti peeved_talking = Image("{{assets}}/sprite/MARSTI_peeved_talking.png", ypos=730)
image marsti shrug = Image("{{assets}}/sprite/MARSTI_shrug.png", ypos=730)
image marsti shrug_talking = Image("{{assets}}/sprite/MARSTI_shrug_talking.png", ypos=730)
image marsti smile = Image("{{assets}}/sprite/MARSTI_smile.png", ypos=730)
image marsti worried = Image("{{assets}}/sprite/MARSTI_worried.png", ypos=730)

# ../custom_volumes_other/hiveswap\marvus.rpy
define marvus = Character(name="MARVUS", kind=hiveswap, image="marvus", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image marvus annoyed = Image("{{assets}}/sprite/marvus_annoyed.png", ypos=730)
image marvus burnt babbling = Image("{{assets}}/sprite/marvus_burnt babbling.png", ypos=730)
image marvus burnt HoldinUp = Image("{{assets}}/sprite/marvus_burnt HoldinUp.png", ypos=730)
image marvus burnt JustToasty = Image("{{assets}}/sprite/marvus_burnt JustToasty.png", ypos=730)
image marvus burnt = Image("{{assets}}/sprite/marvus_burnt.png", ypos=730)
image marvus BurntUpButStillTurntUp = Image("{{assets}}/sprite/marvus_BurntUpButStillTurntUp.png", ypos=730)
image marvus casual aw shiz = Image("{{assets}}/sprite/marvus_casual aw shiz.png", ypos=730)
image marvus casual flattered = Image("{{assets}}/sprite/marvus_casual flattered.png", ypos=730)
image marvus casual shrug = Image("{{assets}}/sprite/marvus_casual shrug.png", ypos=730)
image marvus casual talking smug = Image("{{assets}}/sprite/marvus_casual talking smug.png", ypos=730)
image marvus casual talking = Image("{{assets}}/sprite/marvus_casual talking.png", ypos=730)
image marvus casual winkyface = Image("{{assets}}/sprite/marvus_casual winkyface.png", ypos=730)
image marvus casual = Image("{{assets}}/sprite/marvus_casual.png", ypos=730)
image marvus disgust = Image("{{assets}}/sprite/marvus_disgust.png", ypos=730)
image marvus HearTheCrowd WhatYallSay = Image("{{assets}}/sprite/marvus_HearTheCrowd WhatYallSay.png", ypos=730)
image marvus HearTheCrowd = Image("{{assets}}/sprite/marvus_HearTheCrowd.png", ypos=730)
image marvus hug = Image("{{assets}}/sprite/marvus_hug.png", ypos=730)
image marvus neutral talking = Image("{{assets}}/sprite/marvus_neutral talking.png", ypos=730)
image marvus neutral = Image("{{assets}}/sprite/marvus_neutral.png", ypos=730)
image marvus openarms talking = Image("{{assets}}/sprite/marvus_openarms talking.png", ypos=730)
image marvus openarms = Image("{{assets}}/sprite/marvus_openarms.png", ypos=730)
image marvus pan sprite = Image("{{assets}}/sprite/marvus_pan sprite.png", ypos=730)
image marvus raiseblade = Image("{{assets}}/sprite/marvus_raiseblade.png", ypos=730)
image marvus rank = Image("{{assets}}/sprite/marvus_rank.png", ypos=730)
image marvus rapping = Image("{{assets}}/sprite/marvus_rapping.png", ypos=730)
image marvus shameless = Image("{{assets}}/sprite/marvus_shameless.png", ypos=730)
image marvus shielding = Image("{{assets}}/sprite/marvus_shielding.png", ypos=730)
image marvus STAB look = Image("{{assets}}/sprite/marvus_STAB look.png", ypos=730)
image marvus STAB = Image("{{assets}}/sprite/marvus_STAB.png", ypos=730)
image marvus thinking = Image("{{assets}}/sprite/marvus_thinking.png", ypos=730)
image marvus u naughty = Image("{{assets}}/sprite/marvus_u naughty.png", ypos=730)
image marvus withdrawblade wink = Image("{{assets}}/sprite/marvus_withdrawblade wink.png", ypos=730)
image marvus withdrawblade = Image("{{assets}}/sprite/marvus_withdrawblade.png", ypos=730)
image marvus wtf = Image("{{assets}}/sprite/marvus_wtf.png", ypos=730)

# ../custom_volumes_other/hiveswap\MSPAreader.rpy

# ../custom_volumes_other/hiveswap\nikhee.rpy
define nikhee = Character(name="NIKHEE", kind=hiveswap, image="nikhee", window_background="gui/textbox_blue.png", who_outlines=[(4, "#000056")])

image nikhee blankface = Image("{{assets}}/sprite/nikhee_blankface.png", ypos=730)
image nikhee coward = Image("{{assets}}/sprite/nikhee_coward.png", ypos=730)
image nikhee doiscareyou = Image("{{assets}}/sprite/nikhee_doiscareyou.png", ypos=730)
image nikhee FLEXSTAR_01 = Image("{{assets}}/sprite/nikhee_FLEXSTAR_01.png", ypos=730)
image nikhee FLEXSTAR_02 = Image("{{assets}}/sprite/nikhee_FLEXSTAR_02.png", ypos=730)
image nikhee FLEXSTAR_03 = Image("{{assets}}/sprite/nikhee_FLEXSTAR_03.png", ypos=730)
image nikhee getoutofmysight = Image("{{assets}}/sprite/nikhee_getoutofmysight.png", ypos=730)
image nikhee hemhaw = Image("{{assets}}/sprite/nikhee_hemhaw.png", ypos=730)
image nikhee kylorenlol = Image("{{assets}}/sprite/nikhee_kylorenlol.png", ypos=730)
image nikhee listentome = Image("{{assets}}/sprite/nikhee_listentome.png", ypos=730)
image nikhee lostleg = Image("{{assets}}/sprite/nikhee_lostleg.png", ypos=730)
image nikhee MAYBE = Image("{{assets}}/sprite/nikhee_MAYBE.png", ypos=730)
image nikhee milkflex = Image("{{assets}}/sprite/nikhee_milkflex.png", ypos=730)
image nikhee NO = Image("{{assets}}/sprite/nikhee_NO.png", ypos=730)
image nikhee notimpressed = Image("{{assets}}/sprite/nikhee_notimpressed.png", ypos=730)
image nikhee offended = Image("{{assets}}/sprite/nikhee_offended.png", ypos=730)
image nikhee proud = Image("{{assets}}/sprite/nikhee_proud.png", ypos=730)
image nikhee ringstand = Image("{{assets}}/sprite/nikhee_ringstand.png", ypos=730)
image nikhee smile = Image("{{assets}}/sprite/nikhee_smile.png", ypos=730)
image nikhee THEBRAWNISEUM = Image("{{assets}}/sprite/nikhee_THEBRAWNISEUM.png", ypos=730)
image nikhee weirdflexbutok = Image("{{assets}}/sprite/nikhee_weirdflexbutok.png", ypos=730)
image nikhee weirdflexbutok_scowl = Image("{{assets}}/sprite/nikhee_weirdflexbutok_scowl.png", ypos=730)

# ../custom_volumes_other/hiveswap\objects.rpy
image bgbison = Image("{{assets}}/object/bgbison.png")
image bisonlusus = Image("{{assets}}/object/bisonlusus.png")
image bush = Image("{{assets}}/object/bush.png")
image bush_orig = Image("{{assets}}/object/bush_orig.png")
image cholerbear = Image("{{assets}}/object/cholerbear.png")
image cholerbearhires = Image("{{assets}}/object/cholerbearhires.png")
image ferret_lusus = Image("{{assets}}/object/ferret_lusus.png")
image hatched2dance = Image("{{assets}}/object/hatched2dance.png")
image hors = Image("{{assets}}/object/hors.png")
image lady = Image("{{assets}}/object/lady.png")
image NIHKEEBORG = Image("{{assets}}/object/NIHKEEBORG.png")
image shibasaru = Image("{{assets}}/object/shibasaru.png")
image statue = Image("{{assets}}/object/statue.png")
image tegirijojo = Image("{{assets}}/object/tegirijojo.png")
image zebralusus = Image("{{assets}}/object/zebralusus.png")

# ../custom_volumes_other/hiveswap\polypa.rpy
define polypa = Character(name="POLYPA", kind=hiveswap, image="polypa", window_background="gui/textbox_olive.png", who_outlines=[(4, "#416600")])

image polypa dejected = Image("{{assets}}/sprite/polypa_dejected.png", ypos=730)
image polypa hoodie_intro = Image("{{assets}}/sprite/polypa_hoodie_intro.png", ypos=730)
image polypa hoodie_pissed = Image("{{assets}}/sprite/polypa_hoodie_pissed.png", ypos=730)
image polypa neutral = Image("{{assets}}/sprite/polypa_neutral.png", ypos=730)
image polypa pleased = Image("{{assets}}/sprite/polypa_pleased.png", ypos=730)
image polypa scuffle = Image("{{assets}}/sprite/polypa_scuffle.png", ypos=730)
image polypa serious = Image("{{assets}}/sprite/polypa_serious.png", ypos=730)
image polypa shocked = Image("{{assets}}/sprite/polypa_shocked.png", ypos=730)
image polypa shooshpap = Image("{{assets}}/sprite/polypa_shooshpap.png", ypos=730)

init python:
    quirks["polypa"] = [("(.+)", "<1> *|")]

# ../custom_volumes_other/hiveswap\Remele.rpy
define remele = Character(name="REMELE", kind=hiveswap, image="remele", window_background="gui/textbox_cobalt.png", who_outlines=[(4, "#005682")])

image remele attack = Image("{{assets}}/sprite/Remele_attack.png", ypos=730)
image remele bag = Image("{{assets}}/sprite/Remele_bag.png", ypos=730)
image remele discomfort = Image("{{assets}}/sprite/Remele_discomfort.png", ypos=730)
image remele discomfort_painting = Image("{{assets}}/sprite/Remele_discomfort_painting.png", ypos=730)
image remele grin = Image("{{assets}}/sprite/Remele_grin.png", ypos=730)
image remele Neutral = Image("{{assets}}/sprite/Remele_Neutral.png", ypos=730)
image remele Neutral_after = Image("{{assets}}/sprite/Remele_Neutral_after.png", ypos=730)
image remele pokerface = Image("{{assets}}/sprite/Remele_pokerface.png", ypos=730)
image remele stagger = Image("{{assets}}/sprite/Remele_stagger.png", ypos=730)
image remele wink = Image("{{assets}}/sprite/Remele_wink.png", ypos=730)

# ../custom_volumes_other/hiveswap\Skylla.rpy
define skylla = Character(name="SKYLLA", kind=hiveswap, image="skylla", window_background="gui/textbox_bronze.png", who_outlines=[(4, "#bb6405")])

image skylla anger = Image("{{assets}}/sprite/Skylla_anger.png", ypos=730)
image skylla concern = Image("{{assets}}/sprite/Skylla_concern.png", ypos=730)
image skylla depressed = Image("{{assets}}/sprite/Skylla_depressed.png", ypos=730)
image skylla distress = Image("{{assets}}/sprite/Skylla_distress.png", ypos=730)
image skylla happy = Image("{{assets}}/sprite/Skylla_happy.png", ypos=730)
image skylla kickass = Image("{{assets}}/sprite/Skylla_kickass.png", ypos=730)
image skylla numb = Image("{{assets}}/sprite/Skylla_numb.png", ypos=730)
image skylla numb2 = Image("{{assets}}/sprite/Skylla_numb2.png", ypos=730)
image skylla stand = Image("{{assets}}/sprite/Skylla_stand.png", ypos=730)
image skylla talk = Image("{{assets}}/sprite/Skylla_talk.png", ypos=730)
image skylla upset = Image("{{assets}}/sprite/Skylla_upset.png", ypos=730)

# ../custom_volumes_other/hiveswap\stelsa.rpy
define stelsa = Character(name="STELSA", kind=hiveswap, image="stelsa", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image stelsa embarrassed = Image("{{assets}}/sprite/stelsa_embarrassed.png", ypos=730)
image stelsa embarrassedcasual = Image("{{assets}}/sprite/stelsa_embarrassedcasual.png", ypos=730)
image stelsa fakesmile = Image("{{assets}}/sprite/stelsa_fakesmile.png", ypos=730)
image stelsa fakesmilecasual = Image("{{assets}}/sprite/stelsa_fakesmilecasual.png", ypos=730)
image stelsa gesticulate = Image("{{assets}}/sprite/stelsa_gesticulate.png", ypos=730)
image stelsa gesticulatecasual = Image("{{assets}}/sprite/stelsa_gesticulatecasual.png", ypos=730)
image stelsa happy = Image("{{assets}}/sprite/stelsa_happy.png", ypos=730)
image stelsa happycasual = Image("{{assets}}/sprite/stelsa_happycasual.png", ypos=730)
image stelsa happytowel = Image("{{assets}}/sprite/stelsa_happytowel.png", ypos=730)
image stelsa harried = Image("{{assets}}/sprite/stelsa_harried.png", ypos=730)
image stelsa harriedcasual = Image("{{assets}}/sprite/stelsa_harriedcasual.png", ypos=730)
image stelsa harriedruffled = Image("{{assets}}/sprite/stelsa_harriedruffled.png", ypos=730)
image stelsa smile = Image("{{assets}}/sprite/stelsa_smile.png", ypos=730)
image stelsa smilecasual = Image("{{assets}}/sprite/stelsa_smilecasual.png", ypos=730)
image stelsa smiletowel = Image("{{assets}}/sprite/stelsa_smiletowel.png", ypos=730)
image stelsa surprise = Image("{{assets}}/sprite/stelsa_surprise.png", ypos=730)
image stelsa surprisecasual = Image("{{assets}}/sprite/stelsa_surprisecasual.png", ypos=730)
image stelsa wringing = Image("{{assets}}/sprite/stelsa_wringing.png", ypos=730)
image stelsa wringingcasual = Image("{{assets}}/sprite/stelsa_wringingcasual.png", ypos=730)

# ../custom_volumes_other/hiveswap\Tagora.rpy
define tagora = Character(name="TAGORA", kind=hiveswap, image="tagora", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image tagora clasp = Image("{{assets}}/sprite/Tagora_clasp.png", ypos=730)
image tagora document = Image("{{assets}}/sprite/Tagora_document.png", ypos=730)
image tagora ew = Image("{{assets}}/sprite/Tagora_ew.png", ypos=730)
image tagora helpful = Image("{{assets}}/sprite/Tagora_helpful.png", ypos=730)
image tagora hollering = Image("{{assets}}/sprite/Tagora_hollering.png", ypos=730)
image tagora judging = Image("{{assets}}/sprite/Tagora_judging.png", ypos=730)
image tagora nervous = Image("{{assets}}/sprite/Tagora_nervous.png", ypos=730)
image tagora neutral = Image("{{assets}}/sprite/Tagora_neutral.png", ypos=730)
image tagora neutral2 = Image("{{assets}}/sprite/Tagora_neutral2.png", ypos=730)

init python:
    quirks["tagora"] = [("(.+)", "<1>\n\n*__________")]

# ../custom_volumes_other/hiveswap\tegiri.rpy
define tegiri = Character(name="TEGIRI", kind=hiveswap, image="tegiri", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image tegiri angry = Image("{{assets}}/sprite/tegiri_angry.png", ypos=730)
image tegiri brood = Image("{{assets}}/sprite/tegiri_brood.png", ypos=730)
image tegiri demanding = Image("{{assets}}/sprite/tegiri_demanding.png", ypos=730)
image tegiri doyoudance = Image("{{assets}}/sprite/tegiri_doyoudance.png", ypos=730)
image tegiri doyoudance_fx01 = Image("{{assets}}/sprite/tegiri_doyoudance_fx01.png", ypos=730)
image tegiri doyoudance_fx02 = Image("{{assets}}/sprite/tegiri_doyoudance_fx02.png", ypos=730)
image tegiri neutral = Image("{{assets}}/sprite/tegiri_neutral.png", ypos=730)
image tegiri pleased = Image("{{assets}}/sprite/tegiri_pleased.png", ypos=730)
image tegiri proud = Image("{{assets}}/sprite/tegiri_proud.png", ypos=730)
image tegiri question = Image("{{assets}}/sprite/tegiri_question.png", ypos=730)
image tegiri sharingan = Image("{{assets}}/sprite/tegiri_sharingan.png", ypos=730)
image tegiri sour = Image("{{assets}}/sprite/tegiri_sour.png", ypos=730)
image tegiri talk = Image("{{assets}}/sprite/tegiri_talk.png", ypos=730)
image tegiri thepowerofkamiandanime = Image("{{assets}}/sprite/tegiri_thepowerofkamiandanime.png", ypos=730)

# ../custom_volumes_other/hiveswap\text.rpy
image char bottomspike = Image("{{assets}}/text/bottomspike.png")
image char cashmoney = Image("{{assets}}/text/cashmoney.png")
image char club = Image("{{assets}}/text/club.png")
image char diamond = Image("{{assets}}/text/diamond.png")
image char emoji_peace = Image("{{assets}}/text/emoji_peace.png")
image char heart = Image("{{assets}}/text/heart.png")
image char knifemeter = Image("{{assets}}/text/knifemeter.png")
image char knifemeter1 = Image("{{assets}}/text/knifemeter1.png")
image char knifemeter2 = Image("{{assets}}/text/knifemeter2.png")
image char knifemeter3 = Image("{{assets}}/text/knifemeter3.png")
image char knifemeter4 = Image("{{assets}}/text/knifemeter4.png")
image char knifemeter5 = Image("{{assets}}/text/knifemeter5.png")
image char knife_empty = Image("{{assets}}/text/knife_empty.png")
image char knife_full = Image("{{assets}}/text/knife_full.png")
image char lyneraemoji_happy = Image("{{assets}}/text/lyneraemoji_happy.png")
image char lyneraemoji_mad = Image("{{assets}}/text/lyneraemoji_mad.png")
image char moneygui = Image("{{assets}}/text/moneygui.png")
image char spade = Image("{{assets}}/text/spade.png")
image char topspike = Image("{{assets}}/text/topspike.png")

# ../custom_volumes_other/hiveswap\tirona.rpy
define tirona = Character(name="TIRONA", kind=hiveswap, image="tirona", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image tirona 3whisper_small = Image("{{assets}}/sprite/tirona_3whisper_small.png", ypos=730)
image tirona deerintheheadlights_small = Image("{{assets}}/sprite/tirona_deerintheheadlights_small.png", ypos=730)
image tirona FEASTYOUREYES_small = Image("{{assets}}/sprite/tirona_FEASTYOUREYES_small.png", ypos=730)
image tirona lilhelper_small = Image("{{assets}}/sprite/tirona_lilhelper_small.png", ypos=730)
image tirona memetalk_small = Image("{{assets}}/sprite/tirona_memetalk_small.png", ypos=730)
image tirona meme_small = Image("{{assets}}/sprite/tirona_meme_small.png", ypos=730)
image tirona pigtailyank_small = Image("{{assets}}/sprite/tirona_pigtailyank_small.png", ypos=730)
image tirona secretwhisper_small = Image("{{assets}}/sprite/tirona_secretwhisper_small.png", ypos=730)
image tirona talk_small = Image("{{assets}}/sprite/tirona_talk_small.png", ypos=730)
image tirona WOW_small = Image("{{assets}}/sprite/tirona_WOW_small.png", ypos=730)
image tirona YEAHfrazzled_small = Image("{{assets}}/sprite/tirona_YEAHfrazzled_small.png", ypos=730)
image tirona YEAH_small = Image("{{assets}}/sprite/tirona_YEAH_small.png", ypos=730)

# ../custom_volumes_other/hiveswap\tyzias.rpy
define tyzias = Character(name="TYZIAS", kind=hiveswap, image="tyzias", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image tyzias grimace = Image("{{assets}}/sprite/Tyzias_grimace.png", ypos=730)
image tyzias irritated = Image("{{assets}}/sprite/Tyzias_irritated.png", ypos=730)
image tyzias irritatedtalk = Image("{{assets}}/sprite/Tyzias_irritatedtalk.png", ypos=730)
image tyzias laugh = Image("{{assets}}/sprite/Tyzias_laugh.png", ypos=730)
image tyzias miserable = Image("{{assets}}/sprite/Tyzias_miserable.png", ypos=730)
image tyzias mugglare = Image("{{assets}}/sprite/Tyzias_mugglare.png", ypos=730)
image tyzias sad = Image("{{assets}}/sprite/Tyzias_sad.png", ypos=730)
image tyzias sip = Image("{{assets}}/sprite/Tyzias_sip.png", ypos=730)
image tyzias siplook = Image("{{assets}}/sprite/Tyzias_siplook.png", ypos=730)
image tyzias talk = Image("{{assets}}/sprite/Tyzias_talk.png", ypos=730)
image tyzias weary = Image("{{assets}}/sprite/Tyzias_weary.png", ypos=730)
image tyzias workedup = Image("{{assets}}/sprite/Tyzias_workedup.png", ypos=730)
image tyzias workedup2 = Image("{{assets}}/sprite/Tyzias_workedup2.png", ypos=730)

# ../custom_volumes_other/hiveswap\Vikare.rpy
define vikare = Character(name="VIKARE", kind=hiveswap, image="vikare", window_background="gui/textbox_bronze.png", who_outlines=[(4, "#bb6405")])

image vikare angry = Image("{{assets}}/sprite/Vikare_angry.png", ypos=730)
image vikare conspiracy = Image("{{assets}}/sprite/Vikare_conspiracy.png", ypos=730)
image vikare curious = Image("{{assets}}/sprite/Vikare_curious.png", ypos=730)
image vikare Fractured = Image("{{assets}}/sprite/Vikare_Fractured.png", ypos=730)
image vikare inspired = Image("{{assets}}/sprite/Vikare_inspired.png", ypos=730)
image vikare neutral = Image("{{assets}}/sprite/Vikare_neutral.png", ypos=730)
image vikare sad = Image("{{assets}}/sprite/Vikare_sad.png", ypos=730)
image vikare worried = Image("{{assets}}/sprite/Vikare_worried.png", ypos=730)

# ../custom_volumes_other/hiveswap\vision.rpy

# ../custom_volumes_other/hiveswap\wanshi.rpy
define wanshi = Character(name="WANSHI", kind=hiveswap, image="wanshi", window_background="gui/textbox_jade.png", who_outlines=[(4, "#0aa85b")])

image wanshi betrayed = Image("{{assets}}/sprite/wanshi_betrayed.png", ypos=730)
image wanshi claspshands = Image("{{assets}}/sprite/wanshi_claspshands.png", ypos=730)
image wanshi curiosity = Image("{{assets}}/sprite/wanshi_curiosity.png", ypos=730)
image wanshi eager = Image("{{assets}}/sprite/wanshi_eager.png", ypos=730)
image wanshi expectant = Image("{{assets}}/sprite/wanshi_expectant.png", ypos=730)
image wanshi fear = Image("{{assets}}/sprite/wanshi_fear.png", ypos=730)
image wanshi gift = Image("{{assets}}/sprite/wanshi_gift.png", ypos=730)
image wanshi hi = Image("{{assets}}/sprite/wanshi_hi.png", ypos=730)
image wanshi intro_nothingtoseehere = Image("{{assets}}/sprite/wanshi_intro_nothingtoseehere.png", ypos=730)
image wanshi intro_snitch = Image("{{assets}}/sprite/wanshi_intro_snitch.png", ypos=730)
image wanshi intro_wanshiout = Image("{{assets}}/sprite/wanshi_intro_wanshiout.png", ypos=730)
image wanshi OoO = Image("{{assets}}/sprite/wanshi_OoO.png", ypos=730)
image wanshi rp = Image("{{assets}}/sprite/wanshi_rp.png", ypos=730)
image wanshi sadsmile = Image("{{assets}}/sprite/wanshi_sadsmile.png", ypos=730)
image wanshi shakingwithexcitement = Image("{{assets}}/sprite/wanshi_shakingwithexcitement.png", ypos=730)
image wanshi sideye = Image("{{assets}}/sprite/wanshi_sideye.png", ypos=730)
image wanshi teary = Image("{{assets}}/sprite/wanshi_teary.png", ypos=730)
image wanshi ughlame = Image("{{assets}}/sprite/wanshi_ughlame.png", ypos=730)
image wanshi woah = Image("{{assets}}/sprite/wanshi_woah.png", ypos=730)
image wanshi youknowit = Image("{{assets}}/sprite/wanshi_youknowit.png", ypos=730)

# ../custom_volumes_other/hiveswap\zebede.rpy
define zebede = Character(name="ZEBEDE", kind=hiveswap, image="zebede", window_background="gui/textbox_gold.png", who_outlines=[(4, "#a1a100")])

image zebede crying = Image("{{assets}}/sprite/zebede_crying.png", ypos=730)
image zebede distressed = Image("{{assets}}/sprite/zebede_distressed.png", ypos=730)
image zebede happy = Image("{{assets}}/sprite/zebede_happy.png", ypos=730)
image zebede hi = Image("{{assets}}/sprite/zebede_hi.png", ypos=730)
image zebede neutral = Image("{{assets}}/sprite/zebede_neutral.png", ypos=730)
image zebede questioning = Image("{{assets}}/sprite/zebede_questioning.png", ypos=730)
image zebede radiant = Image("{{assets}}/sprite/zebede_radiant.png", ypos=730)
image zebede shiftyeyed = Image("{{assets}}/sprite/zebede_shiftyeyed.png", ypos=730)
image zebede shockedembarassed = Image("{{assets}}/sprite/zebede_shockedembarassed.png", ypos=730)

# ../custom_volumes_other/hiveswap\zebruh.rpy
define zebruh = Character(name="ZEBRUH", kind=hiveswap, image="zebruh", window_background="gui/textbox_blue.png", who_outlines=[(4, "#000056")])

image zebruh disgust = Image("{{assets}}/sprite/zebruh_disgust.png", ypos=730)
image zebruh displeased = Image("{{assets}}/sprite/zebruh_displeased.png", ypos=730)
image zebruh excited = Image("{{assets}}/sprite/zebruh_excited.png", ypos=730)
image zebruh huh = Image("{{assets}}/sprite/zebruh_huh.png", ypos=730)
image zebruh showoff = Image("{{assets}}/sprite/zebruh_showoff.png", ypos=730)
image zebruh stand = Image("{{assets}}/sprite/zebruh_stand.png", ypos=730)
image zebruh talk = Image("{{assets}}/sprite/zebruh_talk.png", ypos=730)
image zebruh upset = Image("{{assets}}/sprite/zebruh_upset.png", ypos=730)
image zebruh wink = Image("{{assets}}/sprite/zebruh_wink.png", ypos=730)

init python:
    quirks["zebruh_hearts"] = [("(.+)", "{image=char heart} \g<1> {image=char heart}")]
    quirks["zebruh_diamonds"] = [("(.+)", "{image=char diamond} \g<1> {image=char diamond}")]
    quirks["zebruh_clubs"] = [("(.+)", "{image=char club} \g<1> {image=char club}")]
    quirks["zebruh_spades"] = [("(.+)", "{image=char spade} \g<1> {image=char spade}")]

