define boldir = Character(name="BOLDIR", kind=hiveswap, image="boldir", window_background="gui/textbox_olive.png", who_outlines=[(4, "#416600")])

image boldir antidote = Image("{{assets}}/sprite/boldir_antidote.png", ypos=730)
image boldir cold = Image("{{assets}}/sprite/boldir_cold.png", ypos=730)
image boldir cold_small = Image("{{assets}}/sprite/boldir_cold_small.png", ypos=730)
image boldir dressneutral = Image("{{assets}}/sprite/boldir_dressneutral.png", ypos=730)
image boldir dressthoughtful = Image("{{assets}}/sprite/boldir_dressthoughtful.png", ypos=730)
image boldir dresswideeyed = Image("{{assets}}/sprite/boldir_dresswideeyed.png", ypos=730)
image boldir dying = Image("{{assets}}/sprite/boldir_dying.png", ypos=730)
image boldir hurt = Image("{{assets}}/sprite/boldir_hurt.png", ypos=730)
image boldir mean = Image("{{assets}}/sprite/boldir_mean.png", ypos=730)
image boldir mean_small = Image("{{assets}}/sprite/boldir_mean_small.png", ypos=730)
image boldir neutral = Image("{{assets}}/sprite/boldir_neutral.png", ypos=730)
image boldir oof = Image("{{assets}}/sprite/boldir_oof.png", ypos=730)
image boldir thoughtful = Image("{{assets}}/sprite/boldir_thoughtful.png", ypos=730)
image boldir wideeyed = Image("{{assets}}/sprite/boldir_wideeyed.png", ypos=730)
