define charun = Character(name="CHARUN", kind=hiveswap, image="charun", window_background="gui/textbox_olive.png", who_outlines=[(4, "#416600")])

image charun allartisdickingaround = Image("{{assets}}/sprite/charun_allartisdickingaround.png", ypos=730)
image charun bandannaneutral = Image("{{assets}}/sprite/charun_bandannaneutral.png", ypos=730)
image charun bandannaseeanything = Image("{{assets}}/sprite/charun_bandannaseeanything.png", ypos=730)
image charun bandannasquint = Image("{{assets}}/sprite/charun_bandannasquint.png", ypos=730)
image charun canihaveit = Image("{{assets}}/sprite/charun_canihaveit.png", ypos=730)
image charun disappointed = Image("{{assets}}/sprite/charun_disappointed.png", ypos=730)
image charun itsbeautiful = Image("{{assets}}/sprite/charun_itsbeautiful.png", ypos=730)
image charun maybe = Image("{{assets}}/sprite/charun_maybe.png", ypos=730)
image charun neutral_imstuck = Image("{{assets}}/sprite/charun_neutral_imstuck.png", ypos=730)
image charun pleased = Image("{{assets}}/sprite/charun_pleased.png", ypos=730)
image charun quoteinteresting = Image("{{assets}}/sprite/charun_quoteinteresting.png", ypos=730)
image charun squint = Image("{{assets}}/sprite/charun_squint.png", ypos=730)
image charun thereis = Image("{{assets}}/sprite/charun_thereis.png", ypos=730)
image charun tired = Image("{{assets}}/sprite/charun_tired.png", ypos=730)
