define chixie = Character(name="CHIXIE", kind=hiveswap, image="chixie", window_background="gui/textbox_bronze.png", who_outlines=[(4, "#bb6405")])

image chixie annoyed = Image("{{assets}}/sprite/Chixie_annoyed.png", ypos=730)
image chixie crying = Image("{{assets}}/sprite/Chixie_crying.png", ypos=730)
image chixie customerserviceface = Image("{{assets}}/sprite/Chixie_customerserviceface.png", ypos=730)
image chixie dejected = Image("{{assets}}/sprite/Chixie_dejected.png", ypos=730)
image chixie frown = Image("{{assets}}/sprite/Chixie_frown.png", ypos=730)
image chixie happy = Image("{{assets}}/sprite/Chixie_happy.png", ypos=730)
image chixie mad = Image("{{assets}}/sprite/Chixie_mad.png", ypos=730)
image chixie nervous = Image("{{assets}}/sprite/Chixie_nervous.png", ypos=730)
image chixie neutral = Image("{{assets}}/sprite/Chixie_neutral.png", ypos=730)
image chixie ouch = Image("{{assets}}/sprite/Chixie_ouch.png", ypos=730)
image chixie pissed = Image("{{assets}}/sprite/Chixie_pissed.png", ypos=730)
image chixie RAP = Image("{{assets}}/sprite/Chixie_RAP.png", ypos=730)
image chixie sad = Image("{{assets}}/sprite/Chixie_sad.png", ypos=730)
image chixie sadfaygo = Image("{{assets}}/sprite/Chixie_sadfaygo.png", ypos=730)
image chixie shocked = Image("{{assets}}/sprite/Chixie_shocked.png", ypos=730)
image chixie talk = Image("{{assets}}/sprite/Chixie_talk.png", ypos=730)
