define diemen = Character(name="DIEMEN", kind=hiveswap, image="diemen", window_background="gui/textbox_rust.png", who_outlines=[(4, "#a20000")])

image diemen cry = Image("{{assets}}/sprite/diemen_cry.png", ypos=730)
image diemen cry_dogless = Image("{{assets}}/sprite/diemen_cry_dogless.png", ypos=730)
image diemen cry_shirtless = Image("{{assets}}/sprite/diemen_cry_shirtless.png", ypos=730)
image diemen curious = Image("{{assets}}/sprite/diemen_curious.png", ypos=730)
image diemen curious_dogless = Image("{{assets}}/sprite/diemen_curious_dogless.png", ypos=730)
image diemen curious_shirtless = Image("{{assets}}/sprite/diemen_curious_shirtless.png", ypos=730)
image diemen die_shirtless = Image("{{assets}}/sprite/diemen_die_shirtless.png", ypos=730)
image diemen frown = Image("{{assets}}/sprite/diemen_frown.png", ypos=730)
image diemen frown_dogless = Image("{{assets}}/sprite/diemen_frown_dogless.png", ypos=730)
image diemen offer = Image("{{assets}}/sprite/diemen_offer.png", ypos=730)
image diemen offer_dogless = Image("{{assets}}/sprite/diemen_offer_dogless.png", ypos=730)
image diemen offer_dogless_resized = Image("{{assets}}/sprite/diemen_offer_dogless_resized.png", ypos=730)
image diemen offer_shirtless = Image("{{assets}}/sprite/diemen_offer_shirtless.png", ypos=730)
image diemen optimistic = Image("{{assets}}/sprite/diemen_optimistic.png", ypos=730)
image diemen optimistic_dogless = Image("{{assets}}/sprite/diemen_optimistic_dogless.png", ypos=730)
image diemen optimistic_dogless_resized = Image("{{assets}}/sprite/diemen_optimistic_dogless_resized.png", ypos=730)
image diemen optimistic_scaled = Image("{{assets}}/sprite/diemen_optimistic_scaled.png", ypos=730)
image diemen recoil = Image("{{assets}}/sprite/diemen_recoil.png", ypos=730)
image diemen recoil_shirtless = Image("{{assets}}/sprite/diemen_recoil_shirtless.png", ypos=730)
image diemen shock = Image("{{assets}}/sprite/diemen_shock.png", ypos=730)
image diemen shock_shirtless = Image("{{assets}}/sprite/diemen_shock_shirtless.png", ypos=730)
image diemen smile = Image("{{assets}}/sprite/diemen_smile.png", ypos=730)
image diemen smile_dogless = Image("{{assets}}/sprite/diemen_smile_dogless.png", ypos=730)
image diemen smile_dogless_resized = Image("{{assets}}/sprite/diemen_smile_dogless_resized.png", ypos=730)
image diemen smile_scaled = Image("{{assets}}/sprite/diemen_smile_scaled.png", ypos=730)
image diemen smile_shirtless = Image("{{assets}}/sprite/diemen_smile_shirtless.png", ypos=730)
image diemen talk = Image("{{assets}}/sprite/diemen_talk.png", ypos=730)
image diemen talk_dogless = Image("{{assets}}/sprite/diemen_talk_dogless.png", ypos=730)
image diemen talk_dogless_resized = Image("{{assets}}/sprite/diemen_talk_dogless_resized.png", ypos=730)
image diemen thinking = Image("{{assets}}/sprite/diemen_thinking.png", ypos=730)
image diemen thinking_dogless = Image("{{assets}}/sprite/diemen_thinking_dogless.png", ypos=730)
image diemen thinking_dogless_resized = Image("{{assets}}/sprite/diemen_thinking_dogless_resized.png", ypos=730)

init python:
    quirks["diemen"] = [("(.+)", "(| \g<1> |)")]
