define folyklkuprum = Character(name="FOLYKLKUPRUM", kind=hiveswap, image="folyklkuprum", window_background="gui/textbox_gold.png", who_outlines=[(4, "#a1a100")])

image folyklkuprum double frown = Image("{{assets}}/sprite/FOLYKLKUPRUM_double frown.png", ypos=730)
image folyklkuprum doublegrin = Image("{{assets}}/sprite/FOLYKLKUPRUM_doublegrin.png", ypos=730)
image folyklkuprum f_mouthopen = Image("{{assets}}/sprite/FOLYKLKUPRUM_f_mouthopen.png", ypos=730)
image folyklkuprum grin = Image("{{assets}}/sprite/FOLYKLKUPRUM_grin.png", ypos=730)
image folyklkuprum hairtug = Image("{{assets}}/sprite/FOLYKLKUPRUM_hairtug.png", ypos=730)
image folyklkuprum hairtug_angry = Image("{{assets}}/sprite/FOLYKLKUPRUM_hairtug_angry.png", ypos=730)
image folyklkuprum karmsdown = Image("{{assets}}/sprite/FOLYKLKUPRUM_karmsdown.png", ypos=730)
image folyklkuprum k_armpower = Image("{{assets}}/sprite/FOLYKLKUPRUM_k_armpower.png", ypos=730)
image folyklkuprum k_mouthopen = Image("{{assets}}/sprite/FOLYKLKUPRUM_k_mouthopen.png", ypos=730)
image folyklkuprum POWER = Image("{{assets}}/sprite/FOLYKLKUPRUM_POWER.png", ypos=730)
