define karako = Character(name="KARAKO", kind=hiveswap, image="karako", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image karako ATTACK = Image("{{assets}}/sprite/Karako_ATTACK.png", ypos=730)
image karako curious = Image("{{assets}}/sprite/Karako_curious.png", ypos=730)
image karako emo = Image("{{assets}}/sprite/Karako_emo.png", ypos=730)
image karako FEAR = Image("{{assets}}/sprite/Karako_FEAR.png", ypos=730)
image karako grateful = Image("{{assets}}/sprite/Karako_grateful.png", ypos=730)
image karako happy = Image("{{assets}}/sprite/Karako_happy.png", ypos=730)
image karako injured = Image("{{assets}}/sprite/Karako_injured.png", ypos=730)
image karako RLYupset = Image("{{assets}}/sprite/Karako_RLYupset.png", ypos=730)
image karako treestuck = Image("{{assets}}/sprite/Karako_treestuck.png", ypos=730)
image karako upset = Image("{{assets}}/sprite/Karako_upset.png", ypos=730)
