define mallek = Character(name="MALLEK", kind=hiveswap, image="mallek", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image mallek down = Image("{{assets}}/sprite/mallek_down.png", ypos=730)
image mallek drones = Image("{{assets}}/sprite/mallek_drones.png", ypos=730)
image mallek grin = Image("{{assets}}/sprite/mallek_grin.png", ypos=730)
image mallek interest = Image("{{assets}}/sprite/mallek_interest.png", ypos=730)
image mallek laugh = Image("{{assets}}/sprite/mallek_laugh.png", ypos=730)
image mallek lowered = Image("{{assets}}/sprite/mallek_lowered.png", ypos=730)
image mallek neutral = Image("{{assets}}/sprite/mallek_neutral.png", ypos=730)
image mallek pissed = Image("{{assets}}/sprite/mallek_pissed.png", ypos=730)
image mallek really = Image("{{assets}}/sprite/mallek_really.png", ypos=730)
image mallek scrutinyannoyance = Image("{{assets}}/sprite/mallek_scrutinyannoyance.png", ypos=730)
image mallek shirtlessflush = Image("{{assets}}/sprite/mallek_shirtlessflush.png", ypos=730)
image mallek shirtlessmybad = Image("{{assets}}/sprite/mallek_shirtlessmybad.png", ypos=730)
image mallek shirtlesstalk = Image("{{assets}}/sprite/mallek_shirtlesstalk.png", ypos=730)
image mallek shirtlessum = Image("{{assets}}/sprite/mallek_shirtlessum.png", ypos=730)
