define marsti = Character(name="MARSTI", kind=hiveswap, image="marsti", window_background="gui/textbox_rust.png", who_outlines=[(4, "#a20000")])

image marsti angry = Image("{{assets}}/sprite/MARSTI_angry.png", ypos=730)
image marsti browquirk = Image("{{assets}}/sprite/MARSTI_browquirk.png", ypos=730)
image marsti browquirk_talking = Image("{{assets}}/sprite/MARSTI_browquirk_talking.png", ypos=730)
image marsti gogglesup = Image("{{assets}}/sprite/MARSTI_gogglesup.png", ypos=730)
image marsti gogglesup_angry = Image("{{assets}}/sprite/MARSTI_gogglesup_angry.png", ypos=730)
image marsti gogglesup_duh = Image("{{assets}}/sprite/MARSTI_gogglesup_duh.png", ypos=730)
image marsti gogglesup_resigned = Image("{{assets}}/sprite/MARSTI_gogglesup_resigned.png", ypos=730)
image marsti gogglesup_snarky = Image("{{assets}}/sprite/MARSTI_gogglesup_snarky.png", ypos=730)
image marsti Neutral = Image("{{assets}}/sprite/MARSTI_Neutral.png", ypos=730)
image marsti Neutral_talking = Image("{{assets}}/sprite/MARSTI_Neutral_talking.png", ypos=730)
image marsti peeved = Image("{{assets}}/sprite/MARSTI_peeved.png", ypos=730)
image marsti peeved_talking = Image("{{assets}}/sprite/MARSTI_peeved_talking.png", ypos=730)
image marsti shrug = Image("{{assets}}/sprite/MARSTI_shrug.png", ypos=730)
image marsti shrug_talking = Image("{{assets}}/sprite/MARSTI_shrug_talking.png", ypos=730)
image marsti smile = Image("{{assets}}/sprite/MARSTI_smile.png", ypos=730)
image marsti worried = Image("{{assets}}/sprite/MARSTI_worried.png", ypos=730)
