define marvus = Character(name="MARVUS", kind=hiveswap, image="marvus", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image marvus annoyed = Image("{{assets}}/sprite/marvus_annoyed.png", ypos=730)
image marvus burnt babbling = Image("{{assets}}/sprite/marvus_burnt babbling.png", ypos=730)
image marvus burnt HoldinUp = Image("{{assets}}/sprite/marvus_burnt HoldinUp.png", ypos=730)
image marvus burnt JustToasty = Image("{{assets}}/sprite/marvus_burnt JustToasty.png", ypos=730)
image marvus burnt = Image("{{assets}}/sprite/marvus_burnt.png", ypos=730)
image marvus BurntUpButStillTurntUp = Image("{{assets}}/sprite/marvus_BurntUpButStillTurntUp.png", ypos=730)
image marvus casual aw shiz = Image("{{assets}}/sprite/marvus_casual aw shiz.png", ypos=730)
image marvus casual flattered = Image("{{assets}}/sprite/marvus_casual flattered.png", ypos=730)
image marvus casual shrug = Image("{{assets}}/sprite/marvus_casual shrug.png", ypos=730)
image marvus casual talking smug = Image("{{assets}}/sprite/marvus_casual talking smug.png", ypos=730)
image marvus casual talking = Image("{{assets}}/sprite/marvus_casual talking.png", ypos=730)
image marvus casual winkyface = Image("{{assets}}/sprite/marvus_casual winkyface.png", ypos=730)
image marvus casual = Image("{{assets}}/sprite/marvus_casual.png", ypos=730)
image marvus disgust = Image("{{assets}}/sprite/marvus_disgust.png", ypos=730)
image marvus HearTheCrowd WhatYallSay = Image("{{assets}}/sprite/marvus_HearTheCrowd WhatYallSay.png", ypos=730)
image marvus HearTheCrowd = Image("{{assets}}/sprite/marvus_HearTheCrowd.png", ypos=730)
image marvus hug = Image("{{assets}}/sprite/marvus_hug.png", ypos=730)
image marvus neutral talking = Image("{{assets}}/sprite/marvus_neutral talking.png", ypos=730)
image marvus neutral = Image("{{assets}}/sprite/marvus_neutral.png", ypos=730)
image marvus openarms talking = Image("{{assets}}/sprite/marvus_openarms talking.png", ypos=730)
image marvus openarms = Image("{{assets}}/sprite/marvus_openarms.png", ypos=730)
image marvus pan sprite = Image("{{assets}}/sprite/marvus_pan sprite.png", ypos=730)
image marvus raiseblade = Image("{{assets}}/sprite/marvus_raiseblade.png", ypos=730)
image marvus rank = Image("{{assets}}/sprite/marvus_rank.png", ypos=730)
image marvus rapping = Image("{{assets}}/sprite/marvus_rapping.png", ypos=730)
image marvus shameless = Image("{{assets}}/sprite/marvus_shameless.png", ypos=730)
image marvus shielding = Image("{{assets}}/sprite/marvus_shielding.png", ypos=730)
image marvus STAB look = Image("{{assets}}/sprite/marvus_STAB look.png", ypos=730)
image marvus STAB = Image("{{assets}}/sprite/marvus_STAB.png", ypos=730)
image marvus thinking = Image("{{assets}}/sprite/marvus_thinking.png", ypos=730)
image marvus u naughty = Image("{{assets}}/sprite/marvus_u naughty.png", ypos=730)
image marvus withdrawblade wink = Image("{{assets}}/sprite/marvus_withdrawblade wink.png", ypos=730)
image marvus withdrawblade = Image("{{assets}}/sprite/marvus_withdrawblade.png", ypos=730)
image marvus wtf = Image("{{assets}}/sprite/marvus_wtf.png", ypos=730)
