define stelsa = Character(name="STELSA", kind=hiveswap, image="stelsa", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image stelsa embarrassed = Image("{{assets}}/sprite/stelsa_embarrassed.png", ypos=730)
image stelsa embarrassedcasual = Image("{{assets}}/sprite/stelsa_embarrassedcasual.png", ypos=730)
image stelsa fakesmile = Image("{{assets}}/sprite/stelsa_fakesmile.png", ypos=730)
image stelsa fakesmilecasual = Image("{{assets}}/sprite/stelsa_fakesmilecasual.png", ypos=730)
image stelsa gesticulate = Image("{{assets}}/sprite/stelsa_gesticulate.png", ypos=730)
image stelsa gesticulatecasual = Image("{{assets}}/sprite/stelsa_gesticulatecasual.png", ypos=730)
image stelsa happy = Image("{{assets}}/sprite/stelsa_happy.png", ypos=730)
image stelsa happycasual = Image("{{assets}}/sprite/stelsa_happycasual.png", ypos=730)
image stelsa happytowel = Image("{{assets}}/sprite/stelsa_happytowel.png", ypos=730)
image stelsa harried = Image("{{assets}}/sprite/stelsa_harried.png", ypos=730)
image stelsa harriedcasual = Image("{{assets}}/sprite/stelsa_harriedcasual.png", ypos=730)
image stelsa harriedruffled = Image("{{assets}}/sprite/stelsa_harriedruffled.png", ypos=730)
image stelsa smile = Image("{{assets}}/sprite/stelsa_smile.png", ypos=730)
image stelsa smilecasual = Image("{{assets}}/sprite/stelsa_smilecasual.png", ypos=730)
image stelsa smiletowel = Image("{{assets}}/sprite/stelsa_smiletowel.png", ypos=730)
image stelsa surprise = Image("{{assets}}/sprite/stelsa_surprise.png", ypos=730)
image stelsa surprisecasual = Image("{{assets}}/sprite/stelsa_surprisecasual.png", ypos=730)
image stelsa wringing = Image("{{assets}}/sprite/stelsa_wringing.png", ypos=730)
image stelsa wringingcasual = Image("{{assets}}/sprite/stelsa_wringingcasual.png", ypos=730)
