define tyzias = Character(name="TYZIAS", kind=hiveswap, image="tyzias", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image tyzias grimace = Image("{{assets}}/sprite/Tyzias_grimace.png", ypos=730)
image tyzias irritated = Image("{{assets}}/sprite/Tyzias_irritated.png", ypos=730)
image tyzias irritatedtalk = Image("{{assets}}/sprite/Tyzias_irritatedtalk.png", ypos=730)
image tyzias laugh = Image("{{assets}}/sprite/Tyzias_laugh.png", ypos=730)
image tyzias miserable = Image("{{assets}}/sprite/Tyzias_miserable.png", ypos=730)
image tyzias mugglare = Image("{{assets}}/sprite/Tyzias_mugglare.png", ypos=730)
image tyzias sad = Image("{{assets}}/sprite/Tyzias_sad.png", ypos=730)
image tyzias sip = Image("{{assets}}/sprite/Tyzias_sip.png", ypos=730)
image tyzias siplook = Image("{{assets}}/sprite/Tyzias_siplook.png", ypos=730)
image tyzias talk = Image("{{assets}}/sprite/Tyzias_talk.png", ypos=730)
image tyzias weary = Image("{{assets}}/sprite/Tyzias_weary.png", ypos=730)
image tyzias workedup = Image("{{assets}}/sprite/Tyzias_workedup.png", ypos=730)
image tyzias workedup2 = Image("{{assets}}/sprite/Tyzias_workedup2.png", ypos=730)
