define baizli = Character(name="BAIZLI", kind=hiveswap, image="baizli", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image baizli CalmManic = Image("{{assets}}/sprite/BAIZLI_CalmManic.png", ypos=730)
image baizli CalmManicTalk = Image("{{assets}}/sprite/BAIZLI_CalmManicTalk.png", ypos=730)
image baizli CalmMorose = Image("{{assets}}/sprite/BAIZLI_CalmMorose.png", ypos=730)
image baizli CalmMoroseTalk = Image("{{assets}}/sprite/BAIZLI_CalmMoroseTalk.png", ypos=730)
image baizli Confused = Image("{{assets}}/sprite/BAIZLI_Confused.png", ypos=730)
image baizli ConfusedTalking = Image("{{assets}}/sprite/BAIZLI_ConfusedTalking.png", ypos=730)
image baizli Disapproving = Image("{{assets}}/sprite/BAIZLI_Disapproving.png", ypos=730)
image baizli DisapprovingTalk = Image("{{assets}}/sprite/BAIZLI_DisapprovingTalk.png", ypos=730)
image baizli InShadow = Image("{{assets}}/sprite/BAIZLI_InShadow.png", ypos=730)
image baizli Laughing = Image("{{assets}}/sprite/BAIZLI_Laughing.png", ypos=730)
image baizli Neutral = Image("{{assets}}/sprite/BAIZLI_Neutral.png", ypos=730)
image baizli NeutralTalking = Image("{{assets}}/sprite/BAIZLI_NeutralTalking.png", ypos=730)
image baizli Skeptical = Image("{{assets}}/sprite/BAIZLI_Skeptical.png", ypos=730)
image baizli Thinking = Image("{{assets}}/sprite/BAIZLI_Thinking.png", ypos=730)
image baizli ThinkingTalk = Image("{{assets}}/sprite/BAIZLI_ThinkingTalk.png", ypos=730)
