define chahut = Character(name="CHAHUT", kind=hiveswap, image="chahut", window_background="gui/textbox_purple.png", who_outlines=[(4, "#2b0057")])

image chahut blood = Image("{{assets}}/sprite/Chahut_blood.png", ypos=730)
image chahut lazysmile = Image("{{assets}}/sprite/Chahut_lazysmile.png", ypos=730)
image chahut neutral = Image("{{assets}}/sprite/Chahut_neutral.png", ypos=730)
image chahut pissed = Image("{{assets}}/sprite/Chahut_pissed.png", ypos=730)
image chahut pray = Image("{{assets}}/sprite/Chahut_pray.png", ypos=730)
image chahut spray = Image("{{assets}}/sprite/Chahut_spray.png", ypos=730)
image chahut suprise = Image("{{assets}}/sprite/Chahut_suprise.png", ypos=730)
image chahut wince = Image("{{assets}}/sprite/Chahut_wince.png", ypos=730)
