define elwurd = Character(name="ELWURD", kind=hiveswap, image="elwurd", window_background="gui/textbox_cobalt.png", who_outlines=[(4, "#005682")])

image elwurd casualsurprise = Image("{{assets}}/sprite/elwurd_casualsurprise.png", ypos=730)
image elwurd defensive = Image("{{assets}}/sprite/elwurd_defensive.png", ypos=730)
image elwurd fingerguns = Image("{{assets}}/sprite/elwurd_fingerguns.png", ypos=730)
image elwurd frown = Image("{{assets}}/sprite/elwurd_frown.png", ypos=730)
image elwurd handsome = Image("{{assets}}/sprite/elwurd_handsome.png", ypos=730)
image elwurd headtilt = Image("{{assets}}/sprite/elwurd_headtilt.png", ypos=730)
image elwurd interested = Image("{{assets}}/sprite/elwurd_interested.png", ypos=730)
image elwurd pissed = Image("{{assets}}/sprite/elwurd_pissed.png", ypos=730)
image elwurd psh = Image("{{assets}}/sprite/elwurd_psh.png", ypos=730)
image elwurd scowl = Image("{{assets}}/sprite/elwurd_scowl.png", ypos=730)
image elwurd shrug = Image("{{assets}}/sprite/elwurd_shrug.png", ypos=730)
image elwurd smile = Image("{{assets}}/sprite/elwurd_smile.png", ypos=730)
image elwurd ugh = Image("{{assets}}/sprite/elwurd_ugh.png", ypos=730)
