define fozzer = Character(name="FOZZER", kind=hiveswap, image="fozzer", window_background="gui/textbox_rust.png", who_outlines=[(4, "#a20000")])

image fozzer accusatory = Image("{{assets}}/sprite/fozzer_accusatory.png", ypos=730)
image fozzer AirQuotes = Image("{{assets}}/sprite/fozzer_AirQuotes.png", ypos=730)
image fozzer ArmsCrossed = Image("{{assets}}/sprite/fozzer_ArmsCrossed.png", ypos=730)
image fozzer ArmsCrossedDispleased = Image("{{assets}}/sprite/fozzer_ArmsCrossedDispleased.png", ypos=730)
image fozzer ArmsCrossedQuestioning = Image("{{assets}}/sprite/fozzer_ArmsCrossedQuestioning.png", ypos=730)
image fozzer digging = Image("{{assets}}/sprite/fozzer_digging.png", ypos=730)
image fozzer embrace = Image("{{assets}}/sprite/fozzer_embrace.png", ypos=730)
image fozzer estatic = Image("{{assets}}/sprite/fozzer_estatic.png", ypos=730)
image fozzer estaticListening = Image("{{assets}}/sprite/fozzer_estaticListening.png", ypos=730)
image fozzer fistpump = Image("{{assets}}/sprite/fozzer_fistpump.png", ypos=730)
image fozzer LetsShovel = Image("{{assets}}/sprite/fozzer_LetsShovel.png", ypos=730)
image fozzer panicked = Image("{{assets}}/sprite/fozzer_panicked.png", ypos=730)
image fozzer SPOOKED = Image("{{assets}}/sprite/fozzer_SPOOKED.png", ypos=730)
image fozzer squint = Image("{{assets}}/sprite/fozzer_squint.png", ypos=730)
image fozzer thinking = Image("{{assets}}/sprite/fozzer_thinking.png", ypos=730)
image fozzer thinkinghard = Image("{{assets}}/sprite/fozzer_thinkinghard.png", ypos=730)
image fozzer thinkingImpressed = Image("{{assets}}/sprite/fozzer_thinkingImpressed.png", ypos=730)
image fozzer thinkingUnimpressed = Image("{{assets}}/sprite/fozzer_thinkingUnimpressed.png", ypos=730)
