define galekh = Character(name="GALEKH", kind=hiveswap, image="galekh", window_background="gui/textbox_blue.png", who_outlines=[(4, "#000056")])

image galekh disappointedpause = Image("{{assets}}/sprite/galekh_disappointedpause.png", ypos=730)
image galekh expressions001 = Image("{{assets}}/sprite/galekh_expressions001.png", ypos=730)
image galekh frustration = Image("{{assets}}/sprite/galekh_frustration.png", ypos=730)
image galekh glare = Image("{{assets}}/sprite/galekh_glare.png", ypos=730)
image galekh neutral = Image("{{assets}}/sprite/galekh_neutral.png", ypos=730)
image galekh nojacketneutral = Image("{{assets}}/sprite/galekh_nojacketneutral.png", ypos=730)
image galekh nojacketpleased = Image("{{assets}}/sprite/galekh_nojacketpleased.png", ypos=730)
image galekh pissed = Image("{{assets}}/sprite/galekh_pissed.png", ypos=730)
image galekh pleased = Image("{{assets}}/sprite/galekh_pleased.png", ypos=730)
image galekh questioning = Image("{{assets}}/sprite/galekh_questioning.png", ypos=730)
image galekh surprise = Image("{{assets}}/sprite/galekh_surprise.png", ypos=730)
image galekh tattoocrookedsmile = Image("{{assets}}/sprite/galekh_tattoocrookedsmile.png", ypos=730)
image galekh tattooflush = Image("{{assets}}/sprite/galekh_tattooflush.png", ypos=730)
image galekh tattooneutral = Image("{{assets}}/sprite/galekh_tattooneutral.png", ypos=730)
image galekh tattoowince = Image("{{assets}}/sprite/galekh_tattoowince.png", ypos=730)
