define lynera = Character(name="LYNERA", kind=hiveswap, image="lynera", window_background="gui/textbox_jade.png", who_outlines=[(4, "#0aa85b")])

image lynera anguish = Image("{{assets}}/sprite/lynera_anguish.png", ypos=730)
image lynera glare = Image("{{assets}}/sprite/lynera_glare.png", ypos=730)
image lynera itsfine = Image("{{assets}}/sprite/lynera_itsfine.png", ypos=730)
image lynera knifethreat = Image("{{assets}}/sprite/lynera_knifethreat.png", ypos=730)
image lynera knifethreattears = Image("{{assets}}/sprite/lynera_knifethreattears.png", ypos=730)
image lynera maybewhatimdoingis = Image("{{assets}}/sprite/lynera_maybewhatimdoingis.png", ypos=730)
image lynera ohnolookwhatyoumademedo = Image("{{assets}}/sprite/lynera_ohnolookwhatyoumademedo.png", ypos=730)
image lynera ohshit = Image("{{assets}}/sprite/lynera_ohshit.png", ypos=730)
image lynera pissed = Image("{{assets}}/sprite/lynera_pissed.png", ypos=730)
image lynera sadredfeelings = Image("{{assets}}/sprite/lynera_sadredfeelings.png", ypos=730)
image lynera smile = Image("{{assets}}/sprite/lynera_smile.png", ypos=730)
image lynera wellinever = Image("{{assets}}/sprite/lynera_wellinever.png", ypos=730)
image lynera whatmoirails = Image("{{assets}}/sprite/lynera_whatmoirails.png", ypos=730)
image lynera wouldyoureally = Image("{{assets}}/sprite/lynera_wouldyoureally.png", ypos=730)
image lynera wrong = Image("{{assets}}/sprite/lynera_wrong.png", ypos=730)
