define tirona = Character(name="TIRONA", kind=hiveswap, image="tirona", window_background="gui/textbox_teal.png", who_outlines=[(4, "#008282")])

image tirona 3whisper_small = Image("{{assets}}/sprite/tirona_3whisper_small.png", ypos=730)
image tirona deerintheheadlights_small = Image("{{assets}}/sprite/tirona_deerintheheadlights_small.png", ypos=730)
image tirona FEASTYOUREYES_small = Image("{{assets}}/sprite/tirona_FEASTYOUREYES_small.png", ypos=730)
image tirona lilhelper_small = Image("{{assets}}/sprite/tirona_lilhelper_small.png", ypos=730)
image tirona memetalk_small = Image("{{assets}}/sprite/tirona_memetalk_small.png", ypos=730)
image tirona meme_small = Image("{{assets}}/sprite/tirona_meme_small.png", ypos=730)
image tirona pigtailyank_small = Image("{{assets}}/sprite/tirona_pigtailyank_small.png", ypos=730)
image tirona secretwhisper_small = Image("{{assets}}/sprite/tirona_secretwhisper_small.png", ypos=730)
image tirona talk_small = Image("{{assets}}/sprite/tirona_talk_small.png", ypos=730)
image tirona WOW_small = Image("{{assets}}/sprite/tirona_WOW_small.png", ypos=730)
image tirona YEAHfrazzled_small = Image("{{assets}}/sprite/tirona_YEAHfrazzled_small.png", ypos=730)
image tirona YEAH_small = Image("{{assets}}/sprite/tirona_YEAH_small.png", ypos=730)
